Red       848821701  2  2  Q    -      -      -        -         1010    0    0 Kc
Red       848883931  2  1 +Bk   c      r      b        b         1010  100  100 9h 5h 8h Th  As 8c 4s
Red       848884040  2  2  crrrc +kc    +k     +krc     +kc        1010  170    0 9d 7s 3s 4s  4c Kc 8s
Red       848884217  2  1 +Bc   r      rrr    k        k          840  160  160 7d 3h 2c Th  6d 4s 2h
Red       848884341  2  2  cc  +kc    +brc   +k       +k          840  110  220 2h 8c 8d 7c  Qs 9s 5d
Red       848884479  4  4  cc   c      c      f        -          950   90    0 9s 3d Qs 6s
Red       848884605  4  2  crc  k      k      k        k          860   40   45 Ad 7h Ts 2c  Kh 8s 4d
Red       848884705  4  3  c    rrc    c      c        c          865  130  290 4s 5h As 8s  6h 7d 3s
Red       848884804  4  2  c   +br    +kc    +kc      +kc        1025  100  120 Jh Qh 3h 5h  Kd 6c Kh
Red       848884927  4  1 +Brc  cc     k      c        c         1045  110  165 3c 8s As Qc  5c 7s 7h
Red       848885064  4  1 +Bc   c      c     +b       +b         1100   90    0 Tc 9c 4s 4c  5h 3c Kh
Red       848885143  4  1 +Bf   -      -      -        -         1010   10    0 2c
Red       848885262  4  1 +Bc  +b     +bc    +k       +k         1000   80  230 6h 6d Ah Jd  Kh 3s 7h
Red       848885365  4  1 +Bk   b      b      b        b         1150   80  140 8s 6d 3d Tc
Red       848885475  3  2  r   +b     +b     +b       +brrrrrrrr   1210  410  410 As 8d Qc 5h  4h Qs Qd
Red       848885544  3  2  cc  +k      k      k        k         1210   20    0 6d Kd Tc Qh  4d 7d 4c
Red       848885643  4  1 +Bc   rrc   +brrrr +b       +b         1190  290    0 5s 2s 5c Qd  8c 2c 6d
Red       848885717  4  1 +Bf   -      -      -        -          900   10    0 4h
Red       848885822  4  4  cc   bc     c      c        c          890  140    0 Qd Jd 8h Ad  9h Qh 7h
Red       848885942  4  4  c    k      k      c        c          750   50    0 5s 8c 4h 2d  5h Jd 7h
Red       848886021  5  5  c   +kc    +kc     c        r          700  120  200 Kh 6s 4s 8c  3d 7h Jd
Red       848886122  5  3  cc   c      c      cc       c          780  150  245 8c 5h Jh 7h  Qd 5d Qh
Red       848886272  5  4  c   +kc    +kc    +kcf      -          875   70    0 Qh Ac 4c 3d
Red       848886399  5  5  c   +brc   +kc     c        rr         805  180  205 Ad Kc 3s 4s  5s 2c Jd
Red       848886500  5  4  cc   k      b      br       b          830  120    0 9s 4s Jh 9d  2c Ah Jc
Red       848886677  6  3  cc  +kc     f      -        -          710   40    0 7c 7d 4d
Red       848886871  6  3  crc  c      f      -        -          670   50    0 3h Qc 6s
Red       848887199  5  2  cr  +k      r      b        b          620  120  210 As Qh 4h Td  3c 8h 2h
Red       848887437  6  3  c    k      c     +kc      +kc         710   70    0 3c Jh 7c 3h  Th 8s Qd
Red       848888265  3  2  r   +k     +brc   +b       +b          800  140  360 Kc 9h Kd 9c
Red       848888375  3  1 +Bc   c      c      c        c         1020   90    0 4h 8h Qs 6c  Kd Jc 5c
Red       848888459  3  3  rrrrrrc  c      c      c        r          930  220  440 Qc Jd 9d 5d  7h 7c 2c
Red       848888573  3  3  c    k     +kc     k        b         1150   70    0 Ks 5s Qh 2d  Tc Ah Kh
Red       848888671  3  1 +Bk   k      k      c        k         1080   30   60 3d 7c 9c 2d  Kd 9h 3s
Red       848888715  3  2  cc   rc    +br     br      +k         1110  180    0 Qs 6s Ks Jc  As 2c Kd
Red       848888848  4  2  cc  +b      b      b        b          930   90  180 As 2s 9d 8h  Ah 5d 2d
Red       848888940  4  4  c    rc     c     +kc      +kc        1020  100    0 7d 3h Kh Ac  9h 3s 5c
Red       848889058  4  3  r    b      k      rr       rr         920  190  285 Ts 9s Jc 7d  Js 7h 7c
Red       848889214  4  1 +Bk   c      c      f        -         1015   40    0 6c 9s 7s 5d
Red       848889302  4  2  r   +brr   +b     +b        -          975  110  110 3c 8h Ks 7h  5s 6c 8c
Red       848889382  4  3  c   +br    +brr   +b       +b          975  205  258 9d 9s 4c Qs  2c 9h 7d
Red       848889490  3  1 +Bk   b      c      c        c         1028   80   80 3h 4c Tc 6d  7h 3s 8c
Red       848889539  3  3  c    c      f      -        -         1028   20    0 3s 4h Ts
Red       848889581  3  2  c   +k     +b     +b       +b         1008   70    0 Ah 5h Kc Qd  9h 8h Jc
Red       848889649  4  1 +Bf   -      -      -        -          938   10    0 6s
Red       848889735  4  4  r    -      -      -        -          928   20   30 Jc
Red       848889748  4  3  c   +b     +b      -        -          938   40   70 Ac Js 8d
Red       848889812  4  4  rc   k      k      k        k          968   40    0 9h Td Qs 6c  6h 2s 7d
Red       848889897  4  1 +Bk   k      k      k        k          928   10    0 2d 7s Kd 5s  8c Th 9c
Red       848889983  4  1 +Bk   b     +b     +bc      +br         918  140  140 2s 9s Qs Kh  3s As Kc
Red       848890047  4  3  cc   b      rr     b        -          918  140  420 Th As 2d Kd
Red       848890177  4  2  cc   b      b      k        k         1198   50   65 7c 5c 6c Jd  Ah 9s 2s
Red       848890300  4  2  c   +k     +k      k        c         1213   30   35 Kd 4s 5c 3d  Ad 9d 6s
Red       848890360  3  2  f    -      -      -        -         1218    0    0 Qh
Red       848890376  3  2  Q    -      -      -        -         1218    0    0 As
