Moo       826754543  7  4  c    c      f      -        -         1000   30    0 8d Th 2d
Moo       826754657  7  6  c    k      b      b        b          970   80  190 3s 4d 2s 5c  5s 4h 5d
Moo       826754781  8  1 +Bc   kc     kc     kc       kf        1080   70    0 2s 9d Js Ts
Moo       826754916  8  2  c    c      c      c        k         1010   60    0 9h 4h 2c Ac  Jd 6h 2h
Moo       826754981  7  6  c    c      k      f        -          950   20    0 3d 7c Kc 5h
Moo       826755037  7  5  c    cc     kc     kc       kc         930   90  140 9h 5s 5c Td  Ts 6s 7s
Moo       826755164  8  8  c    k      b      k        b          980   50   90 Qc 4h 6h 9s
Moo       826755272  8  4  c    kc     bc    +kc      +kc        1020  100    0 Qc 6s Ad Js  Qd 7c Ah
Moo       826755380  8  3  c    f      Q      -        -          920   20    0 Jc 2s
