DM        825842621  3  1 +Bc   k      c      r        r         2125  120  260 2d 7d 3d 5s  9s 4s Ac
DM        825842692  3  2  rc   rc     c     +krc     +kc        2265  160  330 6s 5c Th 5h  7d 5s Qd
DM        825842750  3  3  r   +b     +b      -        -         2435   50  100 As Ac Qs
DM        825842790  3  1 +Br   b      b      b        b         2485   90  105 4c 8s Jc Th  7h 3d Ad
DM        825842853  3  1 +Bf   -      -      -        -         2500   10    0 8h
DM        825842899  3  1 +Bc   cf     -      -        -         2490   30    0 7h 4h
DM        825842961  3  2  f    -      -      -        -         2460    0    0 Qc
DM        825842994  3  3  cc   c      kf     -        -         2460   30    0 6c 4h Jd
DM        825843037  3  3  r    b      f      -        -         2430   30    0 7s 2h 9d
DM        825843091  3  3  cc   cc     c      c        k         2400   80    0 5s 4h 6s Td  Qd Ad 4s
DM        825843149  3  1 +Bf   -      -      -        -         2320   10    0 7c
DM        825843191  3  3  f    -      -      -        -         2310    0    0 Kd
DM        825843230  3  2  r    b      cc     cc       cc        2310  150    0 Ad 5s 5h Jd  Tc Jh 2d
DM        825843312  3  3  f    -      -      -        -         2160    0    0 Kh
DM        825843353  3  2  r    fQ     -      -        -         2160   20    0 7h Jh
DM        826271033  7  3  r    kc    +kc     k        rc        2140  110  150 3d Kh 5c 3h  6s Ah 2s
DM        826271218  7  1 +Brr  b     +k      cc       c         2180  150  245 4c 7d 7h As  Qh 2s 8d
DM        826271557  7  5  rc   c      c      c        f         2275   80    0 7d 6s 9h Qd
DM        826271764  3  1 +BQ   -      -      -        -         2195   10    0 Qs
