GOD       935924829  4  4  r    b      b      -        -         1000   60  140 Ts 6h Qh
GOD       935924857  4  2  c    b      b      b        -         1080   60  130 5h 8s 3h 4h  7s 6s Ts
GOD       935924897  3  2  r   +b      -      -        -         1150   30   50 7h 9h
GOD       935924921  3  3  r   +b      b      k        f         1170   50    0 8s Kh Tc 2d
GOD       935924956  3  2  f    -      -      -        -         1120    0    0 Ts
GOD       935924990  3  1 +Br  +b      -      -        -         1120   30   50 6c 6h
GOD       935925004  3  1 +Bk   f      -      -        -         1140   10    0 Ts Tc
GOD       935925066  3  1 +Bk   f      -      -        -         1130   10    0 6d 3s
GOD       935925091  3  2  f    -      -      -        -         1120    0    0 6s
GOD       935925139  3  2  r   +b      -      -        -         1120   30   50 Qc 7d
GOD       935925155  3  3  f    -      -      -        -         1140    0    0 Jd
GOD       935925161  3  1 +Bk   k      f      -        -         1140   10    0 5c As 2c
GOD       935925180  3  1 +Bk   k      f      -        -         1130   10    0 6d 2c 3d
GOD       935925202  3  3  f    -      -      -        -         1120    0    0 6c
GOD       935925228  3  2  r   +b      -      -        -         1120   30   70 As Td
GOD       935925243  3  1 +Bk  +b     +k     +kf       -         1160   20    0 Tc Ts 2h 8d
GOD       935925292  3  1 +Bk  +b      -      -        -         1140   20   30 6s Ad
GOD       935925315  3  1 +Bk  +kf     -      -        -         1150   10    0 3d Qc
GOD       935925330  4  4  r    b      -      -        -         1140   30   60 6s 4h
GOD       935925350  4  3  c    r      c      c        r         1170  110  240 3h 7c 9s Kh  5c 4d 6c
GOD       935925399  4  3  r    k     +b     +b       +kc        1300   80  190 Kc 8s 8c 6c  Ks 6h Qd
GOD       935925452  4  2  c    b      k      k        b         1410   40   60 Qh Kd 3c 5h
GOD       935925495  4  2  f    -      -      -        -         1430    0    0 8c
GOD       935925500  4  4  f    -      -      -        -         1430    0    0 Td
GOD       935925509  4  3  r    -      -      -        -         1430   20   30 Ac
GOD       935925523  4  1 +Bk   c      r      b        b         1440  100  220 5s 2h 9h 6d  9c 6h 9s
GOD       935925572  4  1 +Bk   b      k      f        -         1560   20    0 7s 6c 4d Th
GOD       935925623  3  1 +Bk   b      k      k        c         1540   40    0 7h Qc 9d Kc  4d 7c 9c
GOD       935925653  4  2  f    -      -      -        -         1500    0    0 8h
GOD       935925699  4  1 +Bk   b     +b     +b       +b         1500   80  160 2h Td Jh Kd
GOD       935925743  4  4  f    -      -      -        -         1580    0    0 Jd
GOD       935925781  4  2  rc   b      bc     k        k         1580   80    0 Jh Th 9d 6s  Ah 3c 5c
GOD       935925845  4  3  c    c      c      c        c         1500   80    0 4d 9s 5h Kd  As 5d Ts
GOD       935925902  4  4  r    -      -      -        -         1420   20   40 5c
GOD       935925920  4  2  f    -      -      -        -         1440    0    0 6c
GOD       935925927  4  3  f    -      -      -        -         1440    0    0 9h
GOD       935925951  4  1 +Bk  +k     +b     +k       +b         1440   50  100 8h Kh Ac 4h
GOD       935925999  4  1 +Bk  +k      b      b       +b         1490   70  180 2s Js 4s Qs  7s Kh Qc
GOD       935926051  4  3  f    -      -      -        -         1600    0    0 5c
GOD       935926090  4  3  r   +b     +b      b        b         1600   90  170 Kd Jh 2c Qs
GOD       935926133  4  2  f    -      -      -        -         1680    0    0 Ts
GOD       935926139  4  1 +Bk  +bc    +b      -        -         1680   50   90 3h As Ah
GOD       935926179  4  2  cc   c     +bc    +br      +b         1720  150  400 6h Jc 6s Js  9s 8s Qh
GOD       935926235  4  1 +Bk   f      -      -        -         1970   10    0 5c 8d
GOD       935926277  4  3  f    -      -      -        -         1960    0    0 As
GOD       935926384  3  3  c    b      b      b        b         1960   80  200 4s 5s 8c Qc  5c 2s 4d
GOD       935926437  3  2  c   +b     +b      k        f         2080   40    0 Qc 9c 4d Th
GOD       935926474  3  3  r   +b     +b     +b       +b         2040   90  200 Tc Ad 4c 9s  Jd Qd 8s
GOD       935926509  2  1 +Bk   k     +b     +k       +k         2150   30   60 6d 5s 6c Td  4c 2s Ac
GOD       935926631  2  2  c   +k     +k     +b       +b         2190   50  100 Qd 2d 4d 8c  8h Jh 5d
GOD       935926661  2  1 +Bc   f      -      -        -         2240   20    0 7d 6c
GOD       935926676  2  1 +Bk   k      b      -        -         2220   30   40 7c 3s 9c
GOD       935926697  2  2  r    b      k      b        k         2230   50  100 Ad 3c 4h 5s  Td Tc Jc
GOD       935926725  2  1 +Bk  +b     +b     +b       +k         2280   60  120 2h 2c 8s 2s  5s Js As
GOD       935926756  2  2  c   +k     +k     +kf       -         2340   10    0 3h 8c Qd 3d
GOD       935926785  2  1 +Bc   c     +brc   +b       +kc        2330  150    0 6h 7c 7s 5h  Qs 4d 7d
GOD       935926830  2  2  r    -      -      -        -         2180   20   30 As
GOD       935926845  2  2  r   +b      -      -        -         2190   30   50 Ah 6c
GOD       935926858  2  2  r   +b      -      -        -         2210   30   50 Kc 5s
GOD       935926866  2  1 +Br   -      -      -        -         2230   20   30 2c
GOD       935926874  2  2  r   +b     +b     +b       +kc        2240   90  180 Kc 9d Kd 6s  2h 2s 9h
GOD       935926904  2  2  r    b      c      f        -         2330   50    0 7c 3c 2s 4d
GOD       935926940  2  2  r   +b     +b      k        b         2280   70  140 Ad 5d 7c 3s  3d Td 7h
GOD       935926972  2  2  c    b      -      -        -         2350   20   30 Js 2d
GOD       935926989  2  2  c    k      k      k        k         2360   10   20 Th 4d 9s 8s  2h 7c 7h
GOD       935927022  2  1 +Bk   k      b      b        c         2370   70    0 8h 6h 7c 9c  5c Qs Js
GOD       935927074  2  1 +Bf   -      -      -        -         2300   10    0 2s
GOD       935927083  2  1 +Bk  +b     +b      -        -         2290   40   60 2d Ah 5h
GOD       935927109  2  1 +Bf   -      -      -        -         2310   10    0 2c
GOD       935927116  2  2  r   +b     +b     +b        -         2300   70  120 Jh Ac Qd 7c
GOD       935927138  2  1 +Bk   b      c      c        k         2350   60  120 9s 8h 8c Qs  6c 7h Qh
GOD       935927167  2  1 +B    -      -      -        -         2410   10   10 4h
GOD       935927174  2  1 +B    -      -      -        -         2410   10   10 2c
GOD       935927178  2  2  f    -      -      -        -         2410    0    0 8c
GOD       935927184  2  2  r    b      -      -        -         2410   30   50 9h 2h
GOD       935927193  2  2  r   +b     +b      -        -         2430   50   80 Ac 5s Js
GOD       935927207  2  1 +Bk   k      b     +bc      +kf        2460   70    0 7c 4s 5c 4h
GOD       935927240  2  1 +Bc   f      -      -        -         2390   20    0 7c 5h
GOD       935927252  2  1 +Bk   f      -      -        -         2370   10    0 6c 9h
GOD       935927266  2  2  r    -      -      -        -         2360   20   30 8d
GOD       935927273  2  1 +Bc  +bc     c      b        b         2370  100    0 8s Ac 7s 2d  4c Jc 6c
GOD       935927323  2  1 +Bk   b     +b      -        -         2270   40   60 4c 6c 6d
GOD       935927342  2  2  c   +b      b     +b        -         2290   60  100 3s Tc Kh Ks
GOD       935927365  2  1 +B    -      -      -        -         2330   10   10 4s
GOD       935927369  2  1 +B    -      -      -        -         2330   10   10 5h
GOD       935927373  2  2  f    -      -      -        -         2330    0    0 Td
GOD       935927379  2  2  f    -      -      -        -         2330    0    0 8s
GOD       935927385  2  2  r    -      -      -        -         2330   20   30 Jd
GOD       935927392  2  2  r   +b     +b      -        -         2340   50   80 Qd 4d As
GOD       935927408  2  2  c   +k     +k     +k       +k         2370   10    0 Qs 2s Ks 4c  Jd 9d 8d
GOD       935927436  2  2  f    -      -      -        -         2360    0    0 Kd
GOD       935927444  2  2  r    -      -      -        -         2360   20   30 Ts
GOD       935927452  2  1 +Bk  +k     +k     +k       +kf        2370   10    0 5s Qh 3s 7d
GOD       935927479  2  1 +Bf   -      -      -        -         2360   10    0 8d
GOD       935927487  2  2  c   +b     +b      -        -         2350   40   60 Js As 4s
GOD       935927507  2  2  r   +b     +b      -        -         2370   50   80 Ac 2s 2h
GOD       935927521  2  1 +Bk   k      f      -        -         2400   10    0 Qc 3s 6s
GOD       935927536  2  2  f    -      -      -        -         2390    0    0 5s
GOD       935927543  2  1 +Bk   b      b      -        -         2390   40   60 Tc 9d Qc
GOD       935927564  2  2  r    -      -      -        -         2410   20   30 Ah
GOD       935927571  2  1 +B    -      -      -        -         2420   10   10 5d
GOD       935927575  2  1 +Bk   c      f      -        -         2420   20    0 7s 3c 8c
GOD       935927587  2  1 +Bk  +b      -      -        -         2400   20   30 4s Kd
GOD       935927600  2  2  r   +b     +b      b        -         2410   70  120 7s 4d Qh 2h
GOD       935927618  2  2  r   +b     +b     +k       +k         2460   50  100 Ks Qd 4d 8h  Ac 8s Jc
GOD       935927648  2  1 +Br   b     +b     +b        -         2510   70  120 Td 2d Th Ts
GOD       935927675  2  1 +B    -      -      -        -         2560   10   10 5s
GOD       935927680  2  2  r   +b      k      f        -         2560   30    0 7d 3c Qh 5h
GOD       935927704  2  1 +Bk   c      c      b        k         2530   60  120 4s 3d 6s 3s  6d 4h Ac
GOD       935927738  2  1 +B    -      -      -        -         2590   10   10 2c
GOD       935927745  2  1 +Br   b      k      r        b         2590   90  180 2c Ts Kc 2s  Kd As Kh
GOD       935927775  3  3  c   +k     +b     +b       +k         2680   50    0 Kh 3h 8d 9c  Th 9s Ah
GOD       935927822  3  3  r   +b     +b      -        -         2630   50   90 Jd 2c 2s
GOD       935927841  3  1 +Bc  +bc    +kc    +k       +k         2670   60  120 5c Ac 5d Qd  2d 4d 2h
GOD       935927885  2  1 +Bf   -      -      -        -         2730   10    0 Qh
GOD       935927894  2  1 +Bk   k     +b     +b        -         2720   50   80 7c 9c Kh Ad
GOD       935927917  2  1 +Bk  +b      -      -        -         2750   20   30 4h 4d
GOD       935927930  2  1 +B    -      -      -        -         2760   10   10 2h
GOD       935927934  2  1 +Bf   -      -      -        -         2760   10    0 2d
GOD       935927941  2  1 +Bc   c     +kc     c        b         2750   90  180 3h 2c Qd 4s  9d 4h 3d
GOD       935927970  2  2  c   +bc    +kc     c        c         2840   90  180 9c 5h 7d Jh  Tc 2c 8c
GOD       935928014  2  1 +Bf   -      -      -        -         2930   10    0 3d
GOD       935928027  2  1 +Bf   -      -      -        -         2920   10    0 3d
GOD       935928034  2  1 +Bk  +b      -      -        -         2910   20   30 3s 3c
GOD       935928045  2  2  rc  +k     +b     +b       +b         2920   90  180 Jd 2d Kc Qd  3s As Kd
GOD       935928077  2  1 +Bc   c      c      -        -         3010   40   80 5d 2c 4c  3s Ad 5c 3c
