Peg       855697518  8  2  cc  +kc    +bc     c        cf         780  130    0 Ad 5h 5s 9h
Peg       855697667  8  2  f    -      -      -        -          650    0    0 Td
Peg       855697728  8  6  c    k      f      -        -          650   10    0 Kc 8d Tc
Peg       855697781  7  6  c   +k     +kc     f        -          640   30    0 6d Jc 4h Kd
Peg       855697843  6  2  cc  +bc    +k     +b        -          610   60  110 5d Ac Kc Ad
Peg       855697876  6  3  c    c      f      -        -          660   20    0 Tc 3s 9d
Peg       855697900  6  3  c    f      -      -        -          640   10    0 Kc Tc
Peg       855697945  6  2  c    c      f      -        -          630   20    0 Qs Th 9c
Peg       855698011  6  5  f    -      -      -        -          610    0    0 8c
Peg       855698023  6  1 +Bc   c     +kc    +kf       -          610   50    0 3d 5c Tc Ks
Peg       855698074  6  4  c    c      cc     c        c          560  140    0 9s 7c 3d 5s  5h 4c Ah
Peg       855698165  6  4  c    k      kc     k        k          420   30    0 6s 4s Th 3c  Kc 5s Kd
Peg       855698225  6  2  c    Q      -      -        -          390   10    0 Js Td
