DM        855389062  4  2  f    -      -      -        -         1740    0    0 9d
DM        855389124  4  4  c    c      c      k        c         1740   60   80 6c Th 7h 2d  Td 8d As
DM        855389178  5  1 +Bk   k      f      -        -         1760   10    0 2s Kc Qs
DM        855389259  5  5  c   +k      f      -        -         1750   10    0 Ah Qd 8h
DM        855389345  5  5  c   +bc    +bcc   +bc      +kccc      1740  230  345 Jd Js 2c 2h  Td 8c 2d
DM        855389438  5  2  f    -      -      -        -         1855    0    0 9h
DM        855389561  4  1 +Bk   k      f      -        -         1855   10    0 3d Jd 6s
DM        855389632  4  4  f    -      -      -        -         1845    0    0 6h
DM        855389724  4  4  c   +bc     c      c        c         1845   90   95 Th Jh 6s Qc  Qd 6h Jd
DM        855389768  5  5  c   +b     +b     +b       +kc        1850   80    0 Ts Th 7s 3h  4s Kh Ac
DM        855389841  5  3  f    -      -      -        -         1770    0    0 Js
DM        855389854  5  2  c   +b      -      -        -         1770   20   30 Ah Kd
DM        855389906  5  2  r    -      -      -        -         1780   20   30 Ac
DM        855389920  5  1 +Bk   k      k      kf       -         1790   10    0 3c 5s Ah Ks
DM        855390047  5  3  r    c      f      -        -         1780   30    0 As 5h Kc
DM        855390137  5  3  r    -      -      -        -         1750   20   30 Kh
DM        855390161  4  1 +B    -      -      -        -         1760   10   10 3c
DM        855390167  4  3  r    -      -      -        -         1760   20   30 Kd
DM        855390179  4  4  r   +br    +b     +b       +b         1770  110  220 As Ad Jh 7c  Ac 6s 9h
DM        855390218  5  1 +Bk  +b     +b     +kf       -         1880   40    0 3c 3s 2d Th
DM        855390256  5  5  f    -      -      -        -         1840    0    0 7h
DM        855390293  6  1 +Br   b      b      br       r         1840  150  150 4c 6c 2d Qd  Ad 3d Ts
DM        855390358  6  1 +Bk   k     +k      k        f         1840   10    0 4h 9s 9d 2d
DM        855390440  6  6  c    c      cc     b        b         1830  100  150 6h 2c 4s 8d  3c Qh Ac
DM        855390529  6  5  c    k      k     +k       +k         1880   10    0 7s 2c Td Qh  2d 4h 5s
DM        855390589  5  4  f    -      -      -        -         1870    0    0 6h
DM        855390623  5  2  f    -      -      -        -         1870    0    0 6s
DM        855390657  5  5  f    Q      -      -        -         1870    0    0 Jh
