TM        856129119  3  1 +Bk  +kc     c      c        c         1000   80    0 3c 3s 2d 9c  9h 5s 4d
TM        856129159  3  1 +B    -      -      -        -          920   10   10 6s
TM        856129177  3  1 +Bk  +k     +kc    +kf       -          920   30    0 6d Kd Jd 9h
TM        856129212  3  3  c    c      kc    +kc      +kf         890   70    0 3s Jd 7d Js
TM        856129273  3  3  r   +kc    +k     +k       +k          820   30    0 Ad Js Ts Qs  8s 4h 5d
TM        856129312  3  3  c   +k      c      f        -          790   30    0 Ac Th 2h 6h
TM        856129356  3  2  f    -      -      -        -          760    0    0 9h
TM        856129362  3  3  c    c      r      -        -          760   60  100 8d Td Ad
TM        856129408  3  3  r   +b     +b     +kc      +kc         800  100  105 Kd 5c Ts Qh  Qd Jc Kh
TM        856129456  3  3  c    k     +kc     b        k          805   50    0 7h 3h 9s 4h  5s Ts 9h
TM        856129489  3  1 +B    -      -      -        -          755   10   10 5c
TM        856129502  3  3  f    -      -      -        -          755    0    0 8c
TM        856129505  3  3  cc  +b     +b     +b       +kc         755   90  100 Jd Js 5c Qh  As 5h 8h
TM        856129559  4  3  cc   c      r      b        b          765  110  230 Ts 9h 7c 3c  Ad Jd 8h
TM        856129615  4  3  cc   kc     kc     kf       -          885   50    0 Jd 6c Ts 4s
TM        856129696  5  3  c    c      c      f        -          835   40    0 Qd 3d 7h Tc
TM        856129787  7  6  cc   c      c      c        c          795   90    0 3h Js 6h 2s  6s 4d Jh
TM        856129921  6  3  cc   c      ccc    kcc      kc         705  190    0 5h Ts 6c 5d  8h Th 7d
TM        856130032  6  2  cc   kc     kc     kc       b          515   90  175 Qd 2s 4h 6c  Qh 5h 8h
TM        856130172  6  2  cc   ccc    kc     br      +b          600  160  460 5s 8c 3h Ad  6d 9s 7c
TM        856130287  6  2  cc   c      cc     kc       kc         900  110  410 8d Kc 3d 9d  9c Kh 6s
TM        856130405  7  4  cc  +kcc    kcc    kc       kf        1200  150    0 Tc Ah 5s Qh
TM        856130579  7  1 +Bc   cc     cf     -        -         1050   60    0 3s Th Qs
TM        856130660  8  6  f    -      -      -        -          990    0    0 Kd
TM        856130840  7  5  c   +kc     c      kf       -          990   50    0 Ad 5s 4h Qs
TM        856130934  8  6  cc   kc     kc     brc      rcc        940  210  320 2s 6h 5s As  Ks 7h Ac
TM        856131070  8  5  ccc  c      c      cc       k         1050  130  200 5c 7h 6c Jh  8c 8s 7s
TM        856131198  8  5  cc   kc     kc    +kc      +kc        1120   90    0 7h 5s 5h 7s  3s Ac Js
TM        856131329  8  4  cc   c      c      c        c         1030   90  160 Kd 5d 8c As  7c Qd 4c
TM        856131472  6  1 +Br   rc     cc     r        k         1100  200  310 2c 4s Jh 3c  6s 7c 7s
TM        856131613  4  2  f    -      -      -        -         1210    0    0 As
TM        856131631  4  1 +B    -      -      -        -         1210   10   10 2h
TM        856131638  4  3  c    c      c      c        c         1210   80    0 3d 2d 7h Qd  5c 5s Qs
TM        856131736  4  3  f    -      -      -        -         1130    0    0 9d
TM        856131739  4  1 +B    -      -      -        -         1130   10   10 4c
TM        856131741  4  3  f    -      -      -        -         1130    0    0 8h
TM        856131767  5  2  c   +br    +bc    +br      +k         1130  140    0 Tc Th Jd Jh  4d 7h 7s
TM        856131860  5  5  f    -      -      -        -          990    0    0 5s
TM        856131876  5  2  f    -      -      -        -          990    0    0 3c
TM        856131983  5  4  cc   k      cc     f        -          990   80    0 Jh 6c Td 9h
TM        856132048  5  5  c    f      -      -        -          910   10    0 Jh 9s
TM        856132162  5  4  c   +k     +k      c        f          900   30    0 8h 9h 6h 5c
TM        856132211  5  5  c    k      c      c        c          870   70   70 6s 2h 5h Ts  As 9s 2d
TM        856132253  5  5  c    k      c      f        -          870   30    0 8h 3c Kh Qd
TM        856132362  6  5  r   +b     +b     +br      +kc         840  130    0 As 3h 9h Jc  5c Jh 6s
TM        856132434  6  4  c    k      ccc    cc       f          710  170    0 5h 6s 2c 6d
TM        856132543  5  1 +Bk  +k      f      -        -          540   10    0 4s Qh 9s
TM        856132599  5  2  c    c      r     +brr     +b          530  180    0 Ts 9d Js Tc  6d Qd 9s
TM        856132684  6  4  c    k     +kc    +kc      +br         350  130  200 8s Tc Ts Qs  Jc Qh 9h
TM        856132771  6  2  c    c      c      rr       k          420  140  180 6c Ts 8h 9s  6s 7s Ad
TM        856132958  7  7  c   +kc     c      k        c          460   80    0 Kd Js Qs Qc  Kh Ac 8s
TM        856133204  3  1 +Bc  +kf     -      -        -          380   20    0 2d Kd
TM        856133240  3  3  c   +k     +k     +kc      +k          360   30    0 Qs Ks 9d 3d  Ac Qd 4s
TM        856133294  3  1 +Bf   -      -      -        -          330   10    0 4s
TM        856133317  3  1 +Bc   rr     b      b        b          320  120  120 6c 5s 3d 2h  7d 6h 3s
TM        856133360  3  2  r    -      -      -        -          320   20   30 Jd
TM        856133542  3  3  c   +k     +kc    +kc      +kc         330   70    0 Qd Qs Kd 5h  Ac 7h 4c
TM        856133552  3  1 +Bf   -      -      -        -          260   10    0 9s
TM        856133559  3  3  c   +k      c     +b       +kc         250   70    0 As 9s Tc Ts  6d 4d 9d
TM        856133564  3  2  c    k      k      k        f          180   10    0 9s 4c Qh 7h
TM        856133567  3  3  f    -      -      -        -          170    0    0 Jd
TM        856133601  4  2  c    c      b     +b       +bc         170  100    0 Ts 7c 9s 7d  9h Kc Td
TM        856133684  5  1 +Bc   cc     c      cA       -           70   70    0 2s 6d 4s 9s  Kc As 6c
TM        856216885  3  1 +Bf   -      -      -        -         1000   10    0 6h
TM        856216928  3  3  c   +b     +k     +b       +b          990   60   70 3d 3c Tc 3s  7h 2s 5d
TM        856216991  3  3  c   +bc    +b     +b       +b         1000   90  180 Ad 5c Qd As  Ac 9d Jd
TM        856217041  3  3  f    -      -      -        -         1090    0    0 9h
TM        856217067  3  2  c   +k      c      k        c         1090   50    0 Jc Ks 4h 4d  3c Js 6d
TM        856217157  4  3  fQQ  -      -      -        -         1040    0    0 Qd
TM        856217504  2  2  c   +b     +b      -        -         1040   40   60 As 2h 8s
TM        856217527  2  1 +Bc   r     +b      k        c         1060   80   80 7c 5s Ad 7h  4c Th 2d
TM        856217561  2  1 +Bk   k      k      k        f         1060   10    0 7s Qs Th 4d
TM        856217613  2  2  f    -      -      -        -         1050    0    0 Ac
TM        856217630  2  1 +Bk   k      k      k        f         1050   10    0 3c 7c Ah Qs
TM        856217682  2  2  c   +b     +b     +b       +b         1040   80  160 Ks 7s 6s Ah  Kd 4h 7d
TM        856217891  2  1 +Bk   k      k     +k       +b         1120   30   40 2s 3c Qs Ks
TM        856218254  3  3  f    -      -      -        -         1130    0    0 Kc
TM        856218262  3  3  c    k      b      -        -         1130   30   50 9c 4d Ah
TM        856218290  3  2  c   +k     +k     +k       +kf        1150   10    0 Qs Jc Th 2c
TM        856218331  3  1 +Bk  +kc    +kc    +k       +k         1140   40   80 4d 9s Kc Ah  7d 9h 7s
TM        856218447  4  2  c   +k      k      k        k         1180   10    0 8d 6h Kh Qh  9s 3d 2h
TM        856218618  4  3  c   +b      rc    +kc      +kf        1170  110    0 Qs 5s Kd Qd
TM        856218621  4  1 +Bc   c      k      b        b         1060   70   70 3c 6d 9h 2s  Qc 2d Kh
TM        856218701  4  4  f    -      -      -        -         1060    0    0 Qd
TM        856218750  4  4  r    b      b      b        bc        1060  120    0 2h 7h 3h 8d  2c 6h 5d
TM        856218811  4  3  c    rc     ccc    c        c          940  170    0 Qh 3c 9s 4d  Qs 3d 8s
TM        856218932  4  4  c    c      c      c        c          770   80    0 8h 3d Ks Jc  4d Kd As
TM        856219001  4  2  c    k      k      f        -          690   10    0 Td 2s 8c 6h
TM        856219112  4  2  c    b      r      k        k          680   60    0 4c 6h 5d Tc  Kc 3s Js
TM        856219198  4  2  c   +k     +k     +b       +b          620   50   65 Kd Ks 5h Kh  7c 6c 2h
TM        856219255  4  4  c   +k     +k      c        c          635   50   55 Qs Kc 2d Jd  Ks Ts 5c
TM        856219362  4  1 +Bk   c      b      b        k          640   60    0 4c Ac 6d Ks  Td 8d 9d
TM        856219458  4  4  c    c      kc     k        k          580   40  120 Tc As Kh 4h  7s Th 3h
TM        856219540  3  1 +Bc   c      r      b        b          660  110    0 9s 8h 7d 3s  5s 5h Ts
TM        856219597  4  2  c    c      c      c        kf         550   60    0 7s Js Ks 5h
TM        856219665  4  4  c   +b     +b     +k       +k          490   40  100 7h 7c 2c 4h  Kc 8d 9c
TM        856219782  5  1 +Bk   c      c      c        k          550   60  120 3h 6d 2h Jh  Jc Tc 2d
TM        856219848  4  2  c    f      -      -        -          610   10    0 8h Jc
TM        856219903  4  4  c   +k     +k     +k       +kf         600   10    0 Kh 5h 5c Jd
TM        856219943  5  2  cc   b      k      c        c          590   70   85 Qc Ks 4h 2c  2s Kh Ts
TM        856220029  5  2  c   +k     +k     +b        -          605   30   40 5d 5s Js Qs
TM        856220099  5  3  r   +b     +b      b        b          615   90  180 Tc 4c 9d 5d
TM        856220162  5  1 +Bk   k      c      f        -          705   30    0 3c Js Qd 7d
TM        856220225  5  4  c    c     +k     +kc      +k          675   40   45 Ts 4s 8c Kc  Ks 6c Ad
TM        856220306  5  1 +Bk  +k      f      Q        Q          680   10    0 5c Qs Ts
TM        856293824  3  1 +Bk   k      c      k        k          670   30    0 6c 3h 2d 3c  9c Qc As
TM        856294002  2  2  f    -      -      -        -          640    0    0 Th
TM        856294009  2  1 +Bc   b     +b     +b       +b          640   90  160 Th 6s 6c 5d
TM        856294021  2  2  c    c      c      k        k          710   40   80 9h 5s 2s Td  6c 8c 8h
TM        856294060  2  1 +Br  +k     +k     +k       +k          750   20   40 Jh Ac 4d Qs  3h 5d Jd
TM        856294101  2  2  r    r      b      b        b          770  100  180 Jd 6h Td 5s
TM        856294148  2  2  c   +kc    +k     +kc      +b          850   60   60 9c Jd Ts Kh  5s Qd Tc
TM        856294189  2  2  f    -      -      -        -          850    0    0 Qc
TM        856294197  2  1 +Bk   c      c      c        k          850   60    0 Qc 2h 8h 9h  Kd Ts 5s
TM        856294236  2  1 +Bk   c      c      c        c          790   80    0 8c 9c Qs 7h  9d 5s 3h
TM        856294269  2  2  r    r      r      r        r          710  160    0 9h 6h Ad 7h  Th Td 9s
TM        856294315  2  1 +Bc  +kc    +kc    +kc      +kc         550   90    0 8s Js Ac Jh  9h 7s 5c
TM        856294354  2  2  cc  +kc    +b     +b       +b          460   90  180 Ac 3d 9c Jd  9h 9d 3s
TM        856294386  2  1 +B    -      -      -        -          550   10   30 8s
TM        856301887  7  4  c   +k     +b      -        -          560   30   40 Ts Jd 7s
TM        856301932  7  4  cc  +kc    +kc    +kc      +kc         570   90    0 3h 3s Qc Qs  7d 6h Jc
TM        856302168  7  1 +Bk   k      k     +k       +QQ         480   10    0 2c Td 9c Ts
TM        856304391  8  2  cc   k      c      f        -          470   40    0 6s 9h 3s 9c
TM        856304482  7  2  cc   cc    +kc    +kf       -          430   70    0 4d 5d 4s Tc
TM        856304633  7  4  rr  +b     +b     +b       +b          360  110  410 4h 4c 7s 5d  Ac Ah 8h
TM        856304725  8  8  c    c      c      cc       cc         660  120  195 6c 7h 3h 4c  2s Kc 7c
TM        856304837  7  3  cc   c      c     +kc      +b          735   90  190 7c 4s Js Jd  5s 9s 7s
TM        856304889  7  3  r    -      -      -        -          835   20   30 As
TM        856304904  6  1 +Bc   f      -      -        -          845   20    0 2s Qh
TM        856304970  5  1 +Bc   k      kc    +kc      +k          825   60    0 3s 4s 6h 3h  As Qd Qc
TM        856305056  5  5  f    -      -      -        -          765    0    0 9s
TM        856305099  6  1 +Bc   c     +kc    +kc      +kc         765   90    0 2d 7h 7c 3c  Qh Qd 5c
TM        856305185  6  6  r    c      c      f        -          675   60    0 Qs 4h 8c 2c
TM        856305229  6  5  c   +kfQQ   -      -        -          615   10    0 Jd Ts
TM        856316012  7  5  c   +kc    +kc     f        -          605   40    0 9c 6s Kc 2d
TM        856316074  8  3  cc   c      c      k        k          565   50    0 9h 5d 5c 4h  Kh 7c 3s
TM        856316254  8  8  c    c      r     +b       +b          515  110  250 7c 6s 4s Ah  2h 2d 2s
TM        856316338  8  1 +Bc   kc     bc     kc       k          655   90  290 4d Td 5d 8s  2d 4h 9d
TM        856316442  7  5  f    -      -      -        -          855    0    0 9h
TM        856316488  6  3  f    -      -      -        -          855    0    0 3d
TM        856316565  6  6  c   +b     +b     +b       +b          855   90  220 7s Ad 3c 9s  Ac Kd 9d
TM        856316629  7  5  c   +kc     c      c        c          985   80    0 Qs Kd 4h 5d  2s 3s 8c
TM        856316679  7  5  c    c      cc     c        f          905  130    0 8c 9d Ah Qd
TM        856316774  7  5  c    c      r      b        r          775  140  210 8h 7h 6s 4d  2s 6d 2c
TM        856316880  8  4  cc   c      c      c        k          845   70    0 7h 9c 2s 9s  4s 6s 2c
TM        856317063  7  6  f    -      -      -        -          775    0    0 4s
TM        856317228  8  6  cc   c      f      -        -          775   30    0 8c Qc Kd
TM        856317323  7  5  cc   c      c      f        -          745   50    0 7h Js Td 3s
TM        856317421  8  4  QQ   -      -      -        -          695    0    0 8s
TM        856409183  3  1 +Bk   r      c      c        b          695   90  180 5h 6c 4s 2h  Ah 6h As
TM        856409244  4  2  cc   cc     c      ccc      kf         785  170    0 Ac 2c 4d 4h
TM        856409389  5  1 +Bc  +k      c     +b       +b          615  100  280 4h Ad 9d Ac  4c Qd 6c
TM        856409478  6  5  cc   c      br     rr       bc         795  210  650 3s 4h 6h Th  Td 4d As
TM        856409614  6  4  c    c      k      c        f         1235   40    0 Kc 7c 2c 9c
TM        856409712  6  6  cc   ccc    c      f        -         1195   90    0 6d 3h 4c Ks
TM        856409829  6  3  cc   cc     c      c        rr        1105  180  530 8h 6h 7h Jh  7d As Ah
TM        856409957  5  1 +Bcc +kc    +b      br       c         1455  160  260 2c As 4h 6s  7d 5d Qc
TM        856410083  4  2  f    -      -      -        -         1555    0    0 5c
TM        856410116  3  1 +Bc   c     +b     +b       +b         1555  100  260 5s 4d Ad 4h  Qh 6s Ac
TM        856410158  3  1 +Bcc  cc     f      -        -         1715   70    0 8h Jc 4d
TM        856410241  3  3  c   +k     +k     +k       +k         1645   10   20 8s Tc Qh Js  Ad 7s 2c
TM        856410289  3  3  f    -      -      -        -         1655    0    0 6c
TM        856410307  4  1 +Bc   c      f      -        -         1655   30    0 3c Jh Kh
TM        856410371  5  3  f    -      -      -        -         1625    0    0 Th
TM        856410422  5  3  cc   cc     c      k        k         1625   90    0 Js Qs 3s Td  7c 3c Jd
TM        856410563  5  5  c   +br    +bc    +kc      +k         1535  110    0 Ad Ac Js Kc  7h Qs 6s
TM        856410670  5  1 +Bcc  f      -      -        -         1425   40    0 2d Qs
TM        856410751  5  1 +Bc   c      c      cc       fQQ       1385  120    0 5c Qd 7c 8s
TM        856670257  2  2  f    -      -      -        -         1265    0    0 Qs
TM        856670270  2  2  cc   c      c     +kc      +kc        1265   90  180 6s 4d 3h Kh  5h Ad 9d
TM        856670310  4  2  cc   c      c      c        c         1355   90  300 Qs 4d 5s Ad  3d 5d Kd
TM        856670386  4  2  QQ   -      -      -        -         1565    0    0 Jh
TM        856922953  5  2  cc   c      -      -        -         1565   30   80 3d 4h Ad
TM        856923171  3  3  c   +kc    +bc    +bc      +kc        1615  130    0 3c Jh Js 2d  5h Td 5s
TM        856923244  4  1 +Bk  +kf     -      -        -         1485   10    0 2c 9d
TM        856923286  5  1 +Bk   kc    +kc    +k       +b         1475   60  110 3c 5s Qc Ac
TM        856923352  5  3  c    kc     kf     -        -         1525   20    0 7s 8h 3s
TM        856923446  5  5  f    -      -      -        -         1505    0    0 Td
TM        856923578  7  7  c   +kf     -      -        -         1505   10    0 6d Qs
TM        856923759  6  2  cc   f      -      -        -         1495   20    0 Ac 7d
TM        856923851  6  3  c    f      Q      -        -         1475   10    0 7s 4d
TM        856924485  6  6  f    -      -      -        -         1465    0    0 Qc
TM        856924600  7  2  cc   c      c      kf       -         1465   50    0 8c 4d 6c Kc
TM        856924747  7  5  cc   cc     QQ     -        -         1415   40    0 9d Qh 3d
