Parrot    946153909  6  2 Bk  b     -     -         1008   20   35 
Parrot    946153936  6  1 Bcc kcc   brc   brc       1023  220    0 Qd 5c
Parrot    946154056  7  6 f   -     -     -          803    0    0 
Parrot    946154087  7  5 c   k     k     k          803   10    0 4d 6s
Parrot    946154156  7  4 c   k     b     k          793   30   90 5c Ah
Parrot    946154222  7  3 f   -     -     -          853    0    0 
Parrot    946154259  7  2 Bk  k     k     f          853   10    0 
Parrot    946154301  7  1 Bc  kf    -     -          843   10    0 
Parrot    946154354  8  8 c   k     k     f          833   10    0 
Parrot    946154419  8  7 f   -     -     -          823    0    0 
Parrot    946154461  8  6 KQ  -     -     -          823    0    0 
Parrot    946577183  8  4 f   -     -     -          823    0    0 
Parrot    946577293 10  4 rc  kf    -     -          823   30    0 
Parrot    946577416 10  3 f   -     -     -          793    0    0 
Parrot    946577508  9  2 Bk  f     -     -          793   10    0 
Parrot    946577606  8  1 Bc  kc    kf    -          783   20    0 
Parrot    946577690  8  8 f   -     -     -          763    0    0 
Parrot    946577741  8  7 r   brc   b     b          763  100  230 Ah Jc
Parrot    946577820  7  5 f   -     -     -          893    0    0 
Parrot    946577888  7  4 r   b     b     b          893   70  170 
Parrot    946577957  7  4 f   -     -     -          993    0    0 
Parrot    946578019  7  2 Bk  kc    kf    -          993   20    0 
Parrot    946578143  6  1 Bf  -     -     -          973    5    0 
Parrot    946578196  4  4 f   -     -     -          968    0    0 
Parrot    946578249  5  3 c   k     f     -          968   10    0 
Parrot    946578299  5  2 Brc c     c     c          958   90    0 9d Ac
Parrot    946578374  7  1 BQ  -     -     -          868    5    0 
