Mo        815431074  6  6  c    cc     c      r        r          685  140  215 6c 5d 4s Jh  Th Ah 3d
Mo        815431194  6  6  f    -      -      -        -          760    0    0 Tc
Mo        815431250  7  5  f    -      -      -        -          760    0    0 Jd
Mo        815431275  6  3  c    c      c     +b       +b          760   80  160 5s 7d 3c Ac  7s 2d 4d
Mo        815431360  6  6  c    c      c      c        c          840   90  230 Kh Qd 5h 2s  2d 5c Kc
Mo        815431451  6  6  f    -      -      -        -          980    0    0 Kc
Mo        815431479  6  3  f    -      -      -        -          980    0    0 As
Mo        815431538  6  6  c   +kc    +kc     c        c          980   80    0 6d Ac Jh 4d  6c 4h 8s
Mo        815431649  5  1 +Bf   -      -      -        -          900   10    0 5c
Mo        815431686  6  3  f    -      -      -        -          890    0    0 7s
Mo        815431763  6  6  f    -      -      -        -          890    0    0 6s
Mo        815431881  7  1 +Bk   c      f      -        -          890   20    0 3s 7d Qs
Mo        815431948  7  7  cc  +k     +b     +b       +b          870   80  200 Tc Th As 5c  4c Ks Ts
Mo        815432102  7  2  Q    -      -      -        -          990    0    0 Kh
