mel       815437534  6  3  c    k     +k      c        c         1000   50   65 6d 5h Ac 7d  3d 8s 3c
mel       815437675  6  3  f    -      -      -        -         1015    0    0 5h
mel       815437729  6  2  f    -      -      -        -         1015    0    0 Ks
mel       815437828  4  1 +BKQ  -      -      -        -         1015   10    0 3d
mel       815963587  4  4  f    -      -      -        -         1005    0    0 Qh
mel       815963664  4  3  c   +b     +b      -        -         1005   40   70 Kd Ks 7s
mel       815963711  4  1 +Bk   f      -      -        -         1035   10    0 7c 4c
mel       815963744  4  2  c   +k      f      -        -         1025   10    0 Ah Qd 3h
mel       815963804  4  3  r    b      b     +bc      +k         1015   90  130 Tc Ad 7d Ts  Td Kc 2c
mel       815963909  4  1 +Br   b      -      -        -         1055   30   50 2h 8h
mel       815963941  4  4  f    -      -      -        -         1075    0    0 9d
mel       815963994  4  2  f    -      -      -        -         1075    0    0 7d
mel       815964120  4  4  c   +k      c     +b       +b         1075   70  140 Qh 3c Kd As  4d Ac 8d
mel       815964190  4  3  f    Q      -      -        -         1145    0    0 8s
mel       816030964  4  1 +Bk   c      f      -        -         1145   20    0 8c 6h Jc
mel       816031003  4  1 +Bf   -      -      -        -         1125   10    0 3c
mel       816031060  4  4  c    k      k     +b        -         1115   30   50 Qs 3c 9d Qc
mel       816031137  4  1 +Bk  +b     +kf     -        -         1135   20    0 8c 8d Kc
mel       816031194  4  3  f    -      -      -        -         1115    0    0 8h
mel       816031241  4  1 +Bk  +b     +b     +k       +k         1115   40   40 4d 4h As Kh  Jh 9c 7d
mel       816031303  4  3  f    -      -      -        -         1115    0    0 Qh
mel       816031325  4  1 +Br   b      b      r        b         1115  110    0 4h 6d 5c Kc  8h Qc Qh
mel       816031446  5  2  r   +k      k      k        b         1005   40   80 Ad Tc Qs 9d
mel       816031549  4  1 +Bk   k      b      -        -         1045   30   40 4d 3d 2d
mel       816031595  4  3  c    b      kc     k        c         1055   60    0 7c 6c Kh 5h  7s Ah Tc
mel       816031748  4  1 +Bk  +b      -      -        -          995   20   40 5d Ac
mel       816031792  3  1 +Bk   f      -      -        -         1015   10    0 4d 9d
mel       816031821  3  2  Q    -      -      -        -         1005    0    0 Qd
mel       816485017  3  1 +B    -      -      -        -         1005   10   10 4c
mel       816485029  3  3  f    -      -      -        -         1005    0    0 Jd
mel       816485046  3  2  r    -      -      -        -         1005   20   30 Th
mel       816485067  4  3  c    c      f      -        -         1015   30    0 5h Ts 3h
mel       816485133  4  2  f    -      -      -        -          985    0    0 Qh
mel       816485154  4  2  c   +kc     c     +bc      +k          985   80   90 8s Jc 6c 8h  5d 9h Js
mel       816485214  4  3  f    -      -      -        -          995    0    0 5h
mel       816485261  3  2  r    -      -      -        -          995   20   30 Ad
mel       816485268  3  1 +Bk  +k      c      k        b         1005   50   80 2h 2c Kd 9d
mel       816485331  3  2  f    Q      -      -        -         1035    0    0 Kd
mel       816645260  7  4  f    -      -      -        -         1035    0    0 8c
mel       816645347  7  5  f    -      -      -        -         1035    0    0 9c
mel       816645365  7  7  c    b      c      f        -         1035   40    0 7s 8c 3h Qh
mel       816645594  6  3  f    -      -      -        -          995    0    0 9c
mel       816645736  7  3  f    -      -      -        -          995    0    0 8d
mel       816645830  8  3  f    -      -      -        -          995    0    0 6s
mel       816645901  8  8  c    c     +bcc    kc       kc         995  140    0 9d Qc 3h 8d  9h 5h 3s
mel       816646061  7  2  c   +k     +b     +kc      +kc         855   70    0 4s Kh Qs Jc  Ac 7h 2s
mel       816646185  6  1 +BQ   -      -      -        -          785   10    0 2d
mel       816910875  5  4  f    -      -      -        -          775    0    0 Tc
mel       816910926  5  2  c    c      f      -        -          775   20    0 8h 3d 9h
mel       816910995  5  2  f    -      -      -        -          755    0    0 Qc
mel       816911013  5  5  f    -      -      -        -          755    0    0 9h
mel       816911051  5  3  f    -      -      -        -          755    0    0 Qs
mel       816911132  5  4  f    -      -      -        -          755    0    0 Ad
mel       816911184  6  1 +Bk   c      k      f        -          755   20    0 3d 4h 2h Ts
mel       816911271  6  1 +Bk   k      k      bc       c          735   70    0 3c 7c 2h Tc  8c 4h 9d
mel       816911359  6  6  c    b     +k     +kc      +kc         665   60   70 7d 5d 7h Js  Ah 2d 6h
mel       816911464  6  3  c    c      c      f        -          675   50    0 Th 7c 4s Qc
mel       816911539  7  2  f    -      -      -        -          625    0    0 Qh
mel       816911594  8  4  f    -      -      -        -          625    0    0 Ad
mel       816911645  8  2  cc   kc     c      c        k          625   70    0 8c Ts 4h Qh  9h 8h 2c
mel       816911792  8  8  cc   bc    +bc     c        k          555  120  240 As 5s 9s 4c  7d 2c 5c
mel       816911922  8  7  c   +k     +b     +b       +bc         675  100    0 As Th Td 7c  7d 4c 4h
mel       816912013  8  1 +Bf   -      -      -        -          575   10    0 2h
mel       816912106  8  5  r    c      c      cc       k          565   90    0 5d Js Kh 9s  Qd Qc 7s
mel       816912210  8  4  f    -      -      -        -          475    0    0 Ac
mel       816912299  8  2  f    -      -      -        -          475    0    0 Ad
mel       816912365  8  8  f    -      Q      -        -          475    0    0 6d
mel       816916215  5  2  f    -      -      -        -          475    0    0 Qc
mel       816916261  5  2  c   +b     +b     +k       +kc         475   60    0 Jc Jh 7h 7d  6c Tc Ah
mel       816916333  5  2  c   +k      k      kc      +b          415   50  110 6s Qd Ts 2d  9d 9c Tc
mel       816916432  5  3  c    r      c      kc       kr         475  110  185 6s 5d 2d 9h  2h 2s Ac
mel       816916550  5  1 +Bk   c     +k     +b        -          550   40   60 4s 5d 4h 8h
mel       816916647  4  4  f    -      -      -        -          570    0    0 8h
mel       816916663  4  3  c    c      c     +kf       -          570   40    0 Qc 3h 6d As
mel       816916747  4  3  c   +kc    +bc    +kf       -          530   60    0 Jc 7s Ah Th
mel       816916832  3  3  r    k     +bc    +k       +b          470   80  140 Jh 5c Ac 4d
mel       816916915  3  3  f    Q      -      -        -          530    0    0 Ad
