DM        816076312  4  2  r    kc     b      -        -         2200   50  125 Ac 8c 7c  Qh Qd Td 5h
DM        816076370  3  1 +Bk   c      k     +b       +b         2275   60  100 5s 9s Ks Kh
DM        816076432  3  2  c   +b     +bc     c        c         2315  100    0 Kd Ah 9s 2h  4c Ad Ts
DM        816076488  3  1 +Bc   cc     c      c        f         2215   90    0 8c Td 5s 7s
DM        816076556  4  1 +Bk   c      c      c        c         2125   80  120 3s Ad 6c 4s  4h 7h Kh
DM        816076609  4  3  f    -      -      -        -         2165    0    0 Jh
DM        816076658  4  1 +Bc   c      r      r        b         2165  130  310 4d 7h 3d 5d  2s Ad Ah
DM        816076733  4  1 +Bc   c      k      c        r         2345   90  125 3d 8d 7d Ac  5d Kh Qs
DM        816076793  4  4  c    f      -      -        -         2380   10    0 5c Td
DM        816076869  4  1 +Bc   cc     c      kc       k         2370  120    0 6s Qs 3d Qd  Jd 5d Ac
DM        816076985  4  2  f    -      -      -        -         2250    0    0 Td
DM        816077126  4  2  c   +k      k      b       +k         2250   30   70 Qc 8c 5d 7h  2c Ah Qs
DM        816077218  4  3  f    -      -      -        -         2290    0    0 2d
DM        816077277  4  3  f    -      -      -        -         2290    0    0 6c
DM        816077294  5  1 +Br   c      b      b        b         2290   90  115 3c 5d 7h 8c  Qs Ad 4d
DM        816077419  5  2  f    -      -      -        -         2315    0    0 Td
DM        816077533  4  3  c    b      k     +k       +kc        2315   40   50 6c 4c Qh Kc  2h 3c 6d
DM        816077617  4  4  r   +b      b     +b       +kc        2325  100  115 As 7d 5h Td  8h 6d 8s
DM        816077668  5  1 +Bk   k      c     +b       +b         2340   70  150 2d 4h 6c As  9d 5d 9h
DM        816077713  5  3  c   +kf     -      -        -         2420   10    0 Qh 8h
DM        816077805  5  5  cc   kc     kc     krc      kc        2410  150    0 Tc 9c 3c Qh  Kc Jh 8h
DM        816077920  5  5  f    -      -      -        -         2260    0    0 4c
DM        816077966  5  2  f    -      -      -        -         2260    0    0 8d
DM        816078050  5  5  f    -      -      -        -         2260    0    0 Qs
DM        816078138  5  3  f    -      -      -        -         2260    0    0 7c
DM        816078192  5  2  rc  +brc   +bc    +kc      +kcc       2260  210    0 Ac Ad 3s 9c  7s 6c 3c
DM        816078295  5  5  r    c     +brc   +br      +k         2050  170  255 8h 7d 8c Jc  2s 3d 8s
DM        816078420  5  1 +Br   b     +bc    +kc      +krc       2135  150    0 4h 2h 2c Kh  Th 6c Ah
DM        816078482  5  5  c    f      -      -        -         1985   10    0 4d Kc
DM        816078564  6  2  r   +b      b      k        rc        1975  110    0 5d 7h 4d 9s  7d 7c Ah
DM        816078613  7  3  rc   kc     f      -        -         1865   50    0 Kd 4h 2s
DM        816078684  6  4  f    -      -      -        -         1815    0    0 Jd
DM        816078749  6  2  r   +b     +kc    +kf       -         1815   50    0 6d Kh Jd Qc
DM        816078789  7  6  f    -      -      -        -         1765    0    0 4d
DM        816078858  7  2  rc   c     +b      f        -         1765   70    0 8s Kc 8h 9c
DM        816078959  7  4  f    Q      -      Q        -         1695    0    0 9d
