mel       818196957  7  3  cc   cc     f      -        -          365   70    0 8s 9h 2c
mel       818197090  8  7  f    -      -      -        -          295    0    0 9h
mel       818197253  8  2  cc   k      c      c        f          295   60    0 Js Qc 3c 6d
mel       818197381  7  4  fQ   -      -      -        -          235    0    0 9h
mel       818292805  8  2  f    -      -      -        -          235    0    0 9h
mel       818292843  8  4  cc   c     +kc    +kc      +b          235   90  340 Ts 5c 5d 7h  Jc 7c 5h
mel       818293033  7  1 +Bf   -      -      -        -          485   10    0 3h
mel       818293151  7  7  f    -      -      -        -          475    0    0 Qc
mel       818293239  7  2  r    b      -      -        -          475   30   50 4d 3s
mel       818293289  7  6  c    c      c      f        -          495   40    0 Jd Td 3h 2c
mel       818293397  8  7  c    kc     k      k        k          455   20    0 3h Jd Qd 4d  As 2h Th
mel       818293509  8  1 +Bc   k      k      b        b          435   60    0 3d Kc 4d 2d  4h 2c Qd
mel       818293582  8  2  f    -      -      -        -          375    0    0 4s
mel       818293607  8  3  f    -      -      -        -          375    0    0 6h
mel       818293693  8  1 +Bk   k      c      c        c          375   70   75 3d Qs 2s 8c  6c Ts 7d
mel       818293755  8  2  c    c      f      -        -          380   20    0 5d Jd Ks
mel       818293840  8  7  c    kc     kf     -        -          360   20    0 8d 4d 9h
mel       818294006  8  3  f    -      -      -        -          340    0    0 3d
mel       818294056  8  5  c    c      c      c        b          340   80    0 6d 5c 5s 4c  Qd Qs 6c
mel       818294128  8  5  f    -      Q      -        -          260    0    0 3s
