Peg       852945964  6  6 c   c     c     c          377   60    0 4h Jd Ts 7s
Peg       852946031  7  5 cc  cc    f     -          317   40    0 
Peg       852946140  8  4 c   kf    -     -          277   10    0 
Peg       852946227  8  3 cr  bc    kc    kf         267   70    0 
Peg       852946359  8  2 Bk  br    b     b          197   80    0 Ts Ad 4s 4c
Peg       852946444  7  1 Bc  kc    kf    Q          117   20    0 
