GOD       935859063  6  1 +Bk  +k     +kc    +kc      +kf        1000   50    0 5d As Qh Ts
GOD       935859160  6  4  cc  +k     +kc    +kc      +kcc        950  100    0 Jh Ac 8s 7c  9h 5h 8h
GOD       935859243  5  5  c    c      f      -        -          850   20    0 Tc 6s 9s
GOD       935859289  6  6  c    k      k      f        -          830   10    0 9s 4c 9d Jh
GOD       935859415  3  1 +Br   b      brc    k        k          820  120    0 5h 2h Jc Ts  7h Qh 4c
GOD       935859481  4  2  c   +k      c     +brc     +kc         700  130    0 Ac 6s 5d As  Qh Kc Qs
GOD       935859520  4  4  f    -      -      -        -          570    0    0 4c
GOD       935859560  4  4  f    -      -      -        -          570    0    0 Th
GOD       935859587  4  3  c    c      f      -        -          570   30    0 Kc 7s 8d
GOD       935859630  4  2  c    k      c      k        c          540   50    0 Jc 9s 7d 3h  7c 6h 5c
GOD       935859660  4  4  f    -      -      -        -          490    0    0 Td
GOD       935859692  4  4  f    -      -      -        -          490    0    0 As
GOD       935859724  4  1 +Bk  +k      b      b        b          490   70   70 6c 8h 7s Td  2h Ah 4c
GOD       935859758  4  4  f    -      -      -        -          490    0    0 Qh
GOD       935859794  4  2  f    Q      -      -        -          490    0    0 3s
