FX        923867129  4  4  f    -      -      -        -         1000    0    0 7d
FX        923867216  5  3  f    -      -      -        -         1000    0    0 7s
FX        923867267  4  4  c   +b     +b     +b       +k         1000   60  150 7h As 3d Ks  Ad 5h 3h
FX        923867314  4  2  cc  +k      c      c        f         1090   60    0 9h 5c Qd 3c
FX        923867356  4  3  c    k      f      -        -         1030   20    0 6h 9d 2c
FX        923867388  4  2  f    -      -      -        -         1010    0    0 Qh
FX        923867444  4  1 +Bk   b      f      -        -         1010   20    0 2h 3h 4s
FX        923867481  4  2  rc   k      k      c        f          990   50    0 As 8s Jh 6s
FX        923867534  4  3  f    -      -      -        -          940    0    0 Ac
FX        923867537  4  4  r    b     +b     +k       +k          940   50    0 5c 8d Kh Jc  3d 5d Qs
FX        923867577  4  3  r    c      f      -        -          890   30    0 As 4s 2h
FX        923867606  4  3  rr   c      c     +b       +b          860  110  200 Js Qc Ac Ah
FX        923867638  4  2  f    -      -      -        -          950    0    0 Ac
FX        923867663  4  2  cc  +b     +b     +b       +b          950   90  190 Kd Kh Ah 5h
FX        923867718  4  1 +Bk  +kc    +kf     -        -         1050   20    0 5d 9c Js
FX        923867737  4  4  r    b      k      c        f         1030   60    0 Qd 8d 5h 4h
FX        923867770  4  3  f    -      -      -        -          970    0    0 9c
FX        923867816  5  2  Q    -      -      -        -          970    0    0 Js
