mrC       800936592  7  2  f    -      -      -        -          700    0    0 Jd
mrC       800936727  8  5  f    -      -      -        -          700    0    0 Td
mrC       800936812  8  8  c    cf     -      -        -          700   30    0 Td Jc
mrC       800936986  8  5  c    f      -      -        -          670   20    0 Td 7h
mrC       800937142  8  3  c    c      k      kc       b          650   60  110 3d Qh Ts Ad  3s 8s 8d
mrC       800937223  8  1 +Bf   -      -      -        -          700   10    0 2c
mrC       800937241  8  3  f    -      -      -        -          690    0    0 Qc
mrC       800937342  8  2  c    c     +kc    +bf       -          690   60    0 6s Kd 5s Kc
mrC       800937473  7  5  f    -      -      -        -          630    0    0 4h
mrC       800937486  7  7  c    c     +krc   +b       +b          630  120    0 Kh 9h Ks 6d  8c 2d Jd
mrC       800937588  7  3  Q    -      -      -        -          510    0    0 Ah
