SK        800400757  7  4  rr   br     b      cr      +bc        1000  220  355 Ad 4h 6s Td  6h 2c 3d
SK        800400983  7  3  f    -      -      -        -         1135    0    0 2d
SK        800401040  7  3  cc   c      r      k        b         1135   90  190 7h 6d 9h 2d  2s 5d 8h
SK        800401119  6  5  c   +k      b     +kf       -         1235   30    0 5s Kd 5c 9h
SK        800401226  6  6  c    c      c      r        f         1205   80    0 Qh 2c 5d 3s
SK        800401329  5  5  r   +b     +b     +bc      +kc        1125  110  110 Td Jh Ac Tc  As 2s 2c
SK        800401388  5  3  r    b      b      k        k         1125   50  110 7d 9d 3c Qh  6d As Qd
SK        800401457  5  4  rr   r     +b     +b       +bc        1185  140    0 Kd 3c 9c As  Ac 3h Kc
SK        800401530  5  1 +Brc  c      c      c        c         1045  110  220 4c As 8c 8h  5d Ks Kc
SK        800401580  5  1 +B    -      -      -        -         1155   10   10 3d
SK        800401594  5  5  f    -      -      -        -         1155    0    0 4c
SK        800401634  5  4  rc   c      f      -        -         1155   50    0 5d Kh Jd
SK        800401685  5  5  r    br     k      b        k         1105   70    0 5s 2c 9d 7c  Ks Ah Jd
SK        800401856  5  1 +Brc  rc    +brc   +b       +b         1035  200    0 3c 2c 3s 7s  Ah 2d 8c
SK        800401942  5  1 +Br   b      br    +k       +k          835   90  230 2h Jc Jh 7d  Ts Th Qc
SK        800402027  5  4  c   +kc    +kr    +kr      +kr         975  140  300 Qh Qd Jh 3d  Qc Qs 8s
SK        800402114  5  2  c    k      b      -        -         1135   30   40 Td 3c 8s
SK        800402175  5  4  r   +b      -      -        -         1145   30   70 Ad Ah
SK        800402207  5  5  rc  +br    +b     +kc      +kc        1185  120    0 8s Td Ks 6c  7c Kd Js
SK        800402271  6  1 +Br   b      b      b        k         1065   70  170 3d Ad 2h 3h  3s Ks 5d
SK        800402368  6  4  r   +b     +b     +b       +kc        1165   90    0 8h 8d Qc Qd  Td 7c 5h
SK        800402484  5  1 +Br   c      c      f        -         1075   70    0 4d Th 6s Qc
SK        800402539  4  3  f    -      -      -        -         1005    0    0 4d
SK        800402547  4  4  f    -      -      -        -         1005    0    0 8s
SK        800402566  4  1 +Bc   c      r      c        rrc       1005  190  190 4c 8c 2h 8d  6s 6h 3c
SK        800402620  4  4  r   +b     +b      b        k         1005   70   75 Ad Kc 7c 6d  7s 4c 5h
SK        800402670  4  2  r   +b      b      r        k         1010   90   90 9s 8h 7s 2h  Ad 3d Kd
SK        800402713  6  1 +B    -      -      -        -         1010   10   10 2h
SK        800402750  5  1 +Bc   r     +b      -        -         1010   60  100 2h Tc Th
SK        800402789  5  4  r    -      -      -        -         1050   20   40 Kh
SK        800402833  5  1 +Br   c      c      c        k         1070   80  160 3c Qd Kd 7h  5s 2h Qs
SK        800402887  6  2  rc   br    +b     +b       +kf        1150  120    0 9h 3h Ac Js
SK        800403013  6  2  f    -      -      -        -         1030    0    0 Kh
SK        800403086  6  2  rr   c      cc     kc       c         1030  130  195 3s Th As Jh  Qs Qd 5d
SK        800403203  6  1 +Brc  krc   +bc    +brc     +kc        1095  220    0 2h 6c Ad 6d  Jd 7h 9h
SK        800403414  6  4  cc  +Q      -      -        -          875   20    0 Kd 6s
