Peg       863463000  8  6  c    b      c     +b       +b          709   80    0 7s 6c Qc Qs  As Ah 6s
Peg       863463081  8  4  cc   kc     f      -        -          629   30    0 7c 6c Ts
Peg       863463238  7  6  cc  +kf     -      -        -          599   40    0 8s Jc
Peg       863463364  6  6  c    k     +kc    +kc      +kc         559   70  260 Qd 5h 5c 8d  4d Ac 8c
Peg       863463459  6  1 +Bf   Q      -      -        -          749   10    0 3c
Peg       864151170  6  4  c    -      -      -        -          739   10   20 8h
Peg       864151264  4  2  cc   k      c      f        -          749   40    0 Ts Qc 4h 9c
Peg       864151338  4  3  cc   c     +k     +k       +kc         709   60  100 Jd 5c Ac 2s  As 9d 6c
Peg       864151422  5  5  f    -      -      -        -          749    0    0 Qh
Peg       864151463  5  3  cc   f      -      -        -          749   30    0 3h Jh
Peg       864151572  5  5  c    k      c      c        k          719   60    0 9d Qh 4s Ac  5d Jd Kh
Peg       864151609  5  4  c   +kc     k      c        c          659   70  110 As Td 3d 3c  4s 6s 3s
Peg       864151672  5  5  c    k      c     +k       +kc         699   50  110 Ts 8c Ah 8d  4c 6c 2d
Peg       864151739  6  4  cc   c      c      rc       c          759  130  510 4h 2c 7s 3s  Qs Qc Qh
Peg       864151880  6  4  cc   cc     ccc   +brc     +bc        1139  260  960 8d 6d Tc Td  Ts Kd Ad
Peg       864152043  6  5  cc   ccc    kcc    kcc      kf        1839  240    0 8d Td 2s 3s
Peg       864152295  7  4  cc   kc     c     +krc     +kc        1599  150    0 6h Js Kh Ks  Ts 9h 6s
Peg       864152482  6  4  f    -      -      Q        -         1449    0    0 5d
