Opal      990379328 10  6 c   kcc   kc    k         1000   90    0 Ad 4d
Opal      990379418  9  4 f   -     -     -          910    0    0 
Opal      990379512  9  3 c   kc    kf    -          910   20    0 
Opal      990379569  9  2 Bk  k     k     b          890   30   90 Js Qh
Opal      990379639  8  1 Bf  -     -     -          950    5    0 
Opal      990379885  6  4 Q   -     -     -          945    0    0 
