ned       849492927  2  2 BrrrrrrrrrrrrrrrrrrrrrrrrrrrrQ -     -     -         1000  570    0 
ned       849576248  2  1 BrrrrrrrrrrQ -     -     -          430  200    0 
ned       849672202  2  1 BrrrrrrrrrQ -     -     -          230  180    0 
ned       849672228  2  1 BcA -     -     -           10   10    0 7h 4h
ned       849672237  2  1 BrrA -     -     -           40   40    0 4h 7h
ned       849672253  2  1 BrrrrrrrrrrrrrrrrrrrrrrrrrrrrQ -     -     -         1000  560    0 
ned       849672280  2  1 BrrrrrrrrrrrrQ -     -     -          440  240    0 
