Moo       826148604  4  4  c    c      k     +b        -         1000   40   80 9c Qh 3c Ah
Moo       826148689  4  4  r   +b     +b      -        -         1040   50   80 Jc 9s Ad
Moo       826148736  4  3  c    c      c      c        c         1070   80    0 Td 5c 6s Jc  Qh 8h Jh
Moo       826148824  4  3  c    b      b      k        b          990   60  130 Tc 2c Qs 4h  8d Kc Ad
Moo       826148914  4  3  cc   c      c      c        -         1060   70  150 8h Qd 2s 9d
Moo       826149077  4  1 +Bk   k      b      b        b         1140   70  120 4h 2d 5s 3h
Moo       826149297  4  2  c    c      c      c        k         1190   60    0 9c 7s 5d Qh  6h Jh 9h
Moo       826149429  6  1 +Bk   kc     kc    +kc      +b         1130   80  190 3d Qh 6h 9s  7d 5c 8c
Moo       826149607  6  1 +Bk  +b     +bc    +b       +b         1240  100  260 3s 3d As 6h  Kc 2h Kd
Moo       826149795  4  2  r    c      k      k        k         1400   30    0 4d 5h 7d Td  2h 9c Jd
Moo       826149963  4  3  fQ   -      -      -        -         1370    0    0 Qh
