Bison     887932927  7  4 f   -     -     -         1000    0    0 
Bison     887932961  7  3 c   kc    k     b         1000   40  100 
Bison     887933027  7  2 Bk  bc    kc    kc        1060   70    0 8h Ah Jh 5s
Bison     887933092  6  1 Bc  kf    -     -          990   10    0 
Bison     887933135  7  6 c   f     -     -          980   10    0 
Bison     887933177  7  5 f   -     -     -          970    0    0 
Bison     887933220  7  4 f   -     -     -          970    0    0 
Bison     887933264  7  3 f   -     -     -          970    0    0 
Bison     887933313  6  2 Bk  kf    -     -          970   10    0 
Bison     887933366  6  1 Bf  -     -     -          960    5    0 
Bison     887933417  7  7 f   -     -     -          955    0    0 
Bison     887933496  5  5 c   c     c     f          955   40    0 
Bison     887933558  6  4 c   kr    r     b          915   90  240 5c Ad 4s Ts
Bison     887933650  7  4 f   -     -     -         1065    0    0 
Bison     887933705  7  3 f   -     -     -         1065    0    0 
Bison     887933769  7  2 Bk  kf    -     -         1065   10    0 
Bison     887933820  7  1 Bc  k     kf    -         1055   10    0 
Bison     887933886  7  3 Q   -     -     -         1045    0    0 
Bison     887933980  6  6 f   -     -     -         1045    0    0 
Bison     887934015  6  5 f   -     -     -         1045    0    0 
Bison     887934061  6  4 f   -     -     -         1045    0    0 
Bison     887934092  5  2 Br  kc    k     kf        1045   30    0 
Bison     887934161  6  1 Bf  -     -     -         1015    5    0 
Bison     887934199  6  6 f   -     -     -         1010    0    0 
Bison     887934225  6  5 c   c     c     f         1010   40    0 
Bison     887934266  6  4 f   -     -     -          970    0    0 
Bison     887934289  6  3 c   kc    b     b          970   60  100 Qc As Jh 4d
Bison     887934341  5  1 Bc  kc    kf    -         1010   30    0 
Bison     887934391  5  1 Bc  kc    kc    k          980   40    0 6c 4c 5c 4s
Bison     887934438  5  5 f   -     -     -          940    0    0 
Bison     887934478  6  5 c   c     c     f          940   40    0 
Bison     887934523  6  4 cc  c     c     c          900   70    0 Tc Td Ac 5s
Bison     887934581  7  4 c   c     k     f          830   20    0 
Bison     887934634  7  3 r   b     bc    kc         810   90    0 Tc Jd Td Qd
Bison     887934684  9  2 Bc  kQ    -     -          720   20    0 
