Mac       850966892  3  1 +Bk   k      k      k        c         1000   30    0 6s Qh 3d 4c  5s 9d 9s
Mac       850966935  3  1 +B    -      -      -        -          970   10   10 2d
Mac       850966944  3  2  c    c      c      c        c          970   80    0 Ac 2s 7d 9d  Jh Kh 3c
Mac       850966990  3  2  c   +b     +k     +bc      +kc         890   80    0 Ad Ah Th Qh  4d 8c 2s
Mac       850967049  3  3  r   +b     +b     +b       +b          810   90  180 Qd Qc 2c Th  Kd Js Td
Mac       850967091  3  1 +Bf   -      -      -        -          900   10    0 4d
Mac       850967115  3  1 +B    -      -      -        -          890   10   10 5c
Mac       850967124  3  1 +Bk   k      k     +k       +k          890   10   20 4s 9c 2h 2c  8c Kh Ad
Mac       850967162  3  1 +Bk   f      -      -        -          900   10    0 3s 2h
Mac       850967185  4  3  cc  +kr     rc     c        k          890  120  120 Ks Qh Ts 7d  7h 5s 3s
Mac       850967257  4  1 +Bk   k      f      -        -          890   10    0 4h 6s Tc
Mac       850967308  4  1 +Bc   c      bc     -        -          880   70  170 4s 3h Ts 5d
Mac       850968160  2  1 +Bk  +k     +b     +kr      +kc        1060   90    0 Ts Ah Ac 3c  2s 9d 3h
Mac       850968207  2  2  c    k      k      k        f          970   10    0 9c 7h 9s 8d
Mac       850968346  3  2  c    k      c      k        k          960   30   90 5h 9d Jc 6c  Js 2c 4s
Mac       850968419  3  3  f    -      -      -        -         1020    0    0 Qd
Mac       850968526  3  1 +B    -      -      -        -         1020   10   10 4h
Mac       850968646  2  2  c   +k      k      k        k         1020   10    0 9h 7h 5d 6h  Ks 4c Js
Mac       850968684  2  2  c   +b     +k     +b       +b         1010   60   60 6s 6h Kh Jd  2c 4h Qs
Mac       850968735  2  2  c   +b     +b     +b        -         1010   60  100 Ac Ah Th Js
Mac       850968796  2  1 +Bk   c      r      b        c         1050  100    0 5s Jd 2d 3d  3h 7s Ts
Mac       850968837  2  2  r   +k      c      c        r          950  100    0 Kc 6d 8c Ts  3c Kd Jc
Mac       850968879  2  2  c   +k      k      c        rc         850   90    0 9s 2s Js 4d  7s 3c 8h
Mac       850968934  2  1 +B    -      -      -        -          760   10   10 5c
Mac       850969090  4  4  c    k      f      -        -          760   10    0 7s Qd 2d
Mac       850969195  4  1 +Bk   k     +b      k        k          750   30    0 2s 5h 5c 3h  Ts 9d 3s
Mac       850969293  4  4  c    c      k      r        b          720   80  150 Tc 8c Ts Qc
Mac       850969370  4  4  c    c     +k     +kf       -          790   20    0 Js Td As 6d
Mac       850969435  4  1 +Bk   k      k      c        c          770   50    0 4d 8d 2s 3d  2d Js 7c
Mac       850969553  4  3  f    -      -      -        -          720    0    0 9d
Mac       850969571  4  1 +B    -      -      -        -          720   10   10 2c
Mac       850969593  4  4  c   +b      b      -        -          720   40   70 Ts Qs 9h
Mac       850969642  4  1 +Bk   c      c      r        r          750  120  240 6d 8c 5c 9c  Kc Ac 8s
Mac       850969694  4  4  c    c     +kf     -        -          870   20    0 9c 2d Ah
Mac       850969772  4  2  c    k      k      c        c          850   50   50 Js 3c Kh 4h  Jd 9d 8s
Mac       850969834  4  1 +Bk   c      r      k        b          850   80  200 2s 3d 8c Jc
Mac       850969907  5  1 +Bk  +kc    +kc    +kc      +kc         970   80   80 4d 7c Td 8d  3c 9s 5c
Mac       850969985  6  3  c   +k     +k     +b        -          970   30   40 8s Js Qh Jd
Mac       850970040  6  3  c    k      b      r        c          980   90  115 7h 8d 4s 5h  3s 2s 2d
Mac       850970130  6  1 +Bk   c      c      c        c         1005   80    0 2h 6s Jh 7c  9h Ts 3s
Mac       850970207  6  3  cc  +kc    +kf     -        -          925   30    0 Ks 9h 3d
Mac       850970311  6  4  r   +b     +k     +b        -          895   50   90 Jd Kd 3h Qc
Mac       850970356  6  1 +Bk   c     +b     +b       +k          935   60  140 3c 5c 5d 3s  Kd 2s Qh
Mac       850970464  6  1 +Bk  +k     +b     +kc      +b         1015   70  170 2d Jd 9d Qh
Mac       850970548  6  1 +Bk   c      c      k        c         1115   60    0 2c 3c 9h Qd  8s As Ks
Mac       850970645  6  4  c    k      c      r        r         1055  110  230 5d 3s 4s 6h  2c 9s 9h
Mac       850970690  6  2  cc   c      c      c        c         1175   90    0 Tc 5c 3s 2d  9d Th 7d
Mac       850970800  6  1 +Bk   k      r      k        b         1085   70   75 3c 6c 2c Ad  Ts 6s 4d
Mac       850970883  6  6  c   +b     +bc    +bc      +kc        1090  120    0 Ah 6s 4c 2c  8h 6h 3s
Mac       850970960  6  2  c    k      b      cf       Q          970   50    0 Kd Qd Jd 5h
