Peg       849725432  7  4  c    c      c      cc       k         1000   80    0 2s 5c Ks Ts  Kh 3s 6h
Peg       849725529  4  2  cc  +kc    +kc    +k       +k          920   50    0 Tc As 9d Qs  2d 6c 3s
Peg       849725621  5  3  c   +k      k      b        -          870   30   40 4h Kh Ah 8h
Peg       849725661  5  2  c   +b      -      -        -          880   20   30 6s 9s
Peg       849725685  5  4  c    c      c      c        k          890   60    0 7s 9s 4d 3d  Th Jh 6c
Peg       849725729  6  2  f    -      -      -        -          830    0    0 8c
Peg       849725773  5  1 +Bk  +b     +kc    +kc      +kf         830   60    0 3s 3d 7h 8h
Peg       849725839  6  4  c   +k     +k      k        k          770   10    0 4h 4d 9d Kc  Ad 3c 8c
Peg       849725939  5  3  c    k      k     +b        -          760   30   50 6d Qc Kh Qs
Peg       849725982  5  1 +Bk   c     +kc    +kc      +kc         780   80    0 5h Qc Qd 4h  7h 9c Tc
Peg       849726047  5  2  c    k      k      rc       k          700   70   75 7c 2c 9c 4s  6s Ah Qh
Peg       849726112  6  1 +Bk   fQ     -      -        -          705   10    0 3d 7d
