Jake      857689456  4  3  r    b      b      k        c         1000   70   75 Qd 7s 2d 5s  8s Th 8d
Jake      857689497  4  2  cc   k      c      k        k         1005   40    0 Tc 7h 6s 8c  8h Qh 2s
Jake      857689557  4  4  c   +k     +kc     c        k          965   50    0 Kh 5d 7c Jh  Th 9d 6s
Jake      857689596  4  1 +Bc  +kc    +kc    +kc      +kf         915   80    0 2d Js Qd 8h
Jake      857689655  4  1 +Bc   cc    +kc    +kc      +kc         835  130    0 2h 5c 5s Ad  Qd Jh 2c
Jake      857689716  5  4  cc   c      c      c        b          705   90  320 9d 6d Ks Js  Kh Qs 9h
Jake      857689802  5  5  r    b      b      r        c          935  110    0 Ac 2d Th Qs  As 4h 2h
Jake      857689847  5  1 +Bk   k      k      c        kf         825   30    0 2d 6h 8s Tc
Jake      857689963  6  3  c   +kc    +kr    +b       +b          795  100  290 7c 7s Td 8h  Ts 8s 5s
Jake      857690050  6  3  c    f      -      -        -          985   10    0 9h 2s
Jake      857690082  5  5  r    b      -      -        -          975   30   60 3h 5s
Jake      857690111  4  1 +B    -      -      -        -         1005   10   10 7h
Jake      857690130  4  1 +Bc   k      k      r        b         1005   80  160 4h 7h 9c Jh  Tc Qh 8c
Jake      857690179  4  4  c   +b      -      -        -         1085   20   30 Ad 5h
Jake      857690204  3  2  r   +bc    +brr   +b       +bc        1095  200    0 7d Td Qd 8c  5d 3c 7s
Jake      857690231  3  1 +Bc   c     +k     +k       +b          895   50   50 2d Tc Td 8s  3c 4s 5d
Jake      857690272  4  3  c   +kc    +kf     -        -          895   30    0 5s Ks 4d
Jake      857690297  4  4  c    c      k      c        f          865   50    0 8s 5s 3d Qc
Jake      857690327  4  2  cc   c      f      -        -          815   30    0 3s Qd 8c
Jake      857690357  4  4  c   +k     +k     +kf       -          785   10    0 As 9c 2s 4h
Jake      857690392  4  2  cc   c      c      c        f          775   70    0 Qh 4h 2s Qc
Jake      857690429  4  2  c   +k     +k     +b        -          705   30   40 Tc Qh Qc Js
Jake      857690452  4  4  c   +k     +b      -        -          715   40   70 Kh Kd Jh
Jake      857690470  4  1 +Br   r      b      b        f          745   90    0 4d 3s 5s Tc
Jake      857690519  4  1 +Bc   c      f      -        -          655   30    0 4h Qs Tc
Jake      857690571  4  2  c   +k     +k     +k       +kf         625   10    0 9c 4s 3h 8c
Jake      857690606  5  4  c    f      -      -        -          615   20    0 5s Qc
Jake      857690665  5  2  Q    -      -      -        -          595    0    0 3h
