TM        857364266  3  3  f    -      -      -        -         1375    0    0 Jc
TM        857364354  4  1 +Bk   c      r      rr       rc        1375  200  250 3d 6s 5d 2s  As Ad Js
TM        857364496  4  4  f    -      -      -        -         1425    0    0 Kd
TM        857364575  4  3  cc  +kc     c     +kc      +kc        1425   90  105 5h Kc 2d 2s  6c Ac 7s
TM        857364699  4  4  cc   k      k      k        c         1440   40  140 Qd Jc 4s 9c  Ah Qh 9h
TM        857364816  4  1 +Bc   c     +kc    +kc      +k         1540   80  260 2h 9h 9d Ks  2c 3c Qc
TM        857364964  4  3  cc   c      c      c        f         1720   70    0 9h 3c As 7s
TM        857365071  4  2  f    -      -      -        -         1650    0    0 Ks
TM        857365115  4  2  cc   kc     br     b        b         1650  130    0 8d 5d 4d Td  Ah Jh Kc
TM        857365179  4  2  cc   cc     c      rc       rc        1520  240  365 6c As 3s 2c  9h Kc 5d
TM        857365387  5  1 +Bk   c      c      c        rr        1645  140  280 3s 4d Tc 8s  4c 5c 4h
TM        857365494  5  2  ccc  kc    +b     +bc      +kc        1785  140  430 Td Kh Ts 2s  7s Tc 5d
TM        857365614  4  3  cf   -      Q      -        -         2075   10    0 Ac
TM        857419879  4  4  c   +k     +k      c        r         1535   70  140 8d 4c 6h 2d  5h As 6s
TM        857420298  4  1 +Bk  +kc     c      f        -         1920   40    0 8d Qh 7c Kh
TM        857431350  3  1 +Bc   rc     c      c        c         1860  110    0 3c 9s Kc 7s  9d 7c 3d
TM        857431390  4  3  c    c      c      f        -         1750   40    0 8d Jh 7h 2s
TM        857431426  4  4  r    -      -      -        -         1710   20   30 Ac
TM        857431495  4  1 +Bk  +b      -      -        -         1720   20   30 3c Ah
TM        857431498  4  1 +Bc  +k     +kc    +kc      +kf        1730   60    0 4s 4h Th 3d
TM        857431519  3  2  cc  +kc    +k     +k       +b         1670   50   50 7s 7h 7d 4s  Jh 6s Js
TM        857431583  4  4  c   +k     +k     +b        -         1670   40   70 Ad Ac 5c 8h
TM        857431620  4  4  c    c      c      c        c         1700   80   90 Jh 4c Qd 9h  9s 3s Jc
TM        857431665  5  1 +Bc  +kc    +kc     f        -         1710   50    0 4s 4h Qc Ts
TM        857432251  4  1 +Bk   k      bc    +b       +b         1555   90  230 5c Kd 3s Kh
TM        857432352  4  1 +Bf   Q      Q      -        -         1695   10    0 4h
TM        857504269  2  2  f    -      -      -        -         1685    0    0 Jc
TM        857504286  2  2  c   +k      c     +k       +b         1685   50   80 As 6s Td 6d
TM        857504342  3  3  f    -      -      -        -         1715    0    0 8s
TM        857504350  3  1 +Bf   -      -      -        -         1715   10    0 4h
TM        857504369  3  2  f    -      -      -        -         1705    0    0 Jd
TM        857504419  4  1 +Bf   -      -      -        -         1705   10    0 3d
TM        857504485  5  4  f    -      -      -        -         1695    0    0 6h
TM        857504486  5  1 +Bf   -      -      -        -         1695   10    0 4c
TM        857504495  5  1 +Bk   c      c      ccc      f         1685  120    0 6s 5h 2c Kd
TM        857504611  5  2  c   +k     +kc    +kc      +kf        1565   50    0 5s 9c Kh Jh
TM        857504666  6  3  f    -      -      -        -         1515    0    0 Qh
TM        857504702  7  1 +Bk   k      r      b        k         1515   70   70 4d 2c 7d 6c  Kh 3h 8c
TM        857504796  8  6  c    c      r      b        rrc       1515  190  245 6d 3d As 8s  2s 4h 8c
TM        857504962  6  2  QQ   -      -      -        -         1570    0    0 Th
TM        857527301  5  3  c    c     +k     +k       +b         1570   40   80 Jd 6c Jc Ac
TM        857527350  5  1 +Bc   c      c      k        k         1610   50    0 4d 9s 3h 6s  Js 8s 8h
TM        857527398  4  1 +Bf   -      -      -        -         1560   10    0 6c
TM        857527463  4  2  cc   k      f      -        -         1550   20    0 Td 3h 2d
TM        857527518  5  3  Q    -      -      -        -         1530    0    0 Kc
TM        857527980  7  3  cc   cc     k      c        f         1530   60    0 4d Jc 5c 5d
TM        857528063  7  2  cc   c      cc     kc       kf        1470   90    0 Ks 9s 2s 3c
TM        857528136  7  4  f    -      -      -        -         1380    0    0 7s
TM        857528168  6  2  rc  +b     +b      b       +b         1380  100  130 Jc 2c 4s 6d  As Ad 4h
TM        857528223  6  5  f    -      -      -        -         1410    0    0 9s
TM        857528261  5  2  c   +k     +kc    +kc      +k         1410   50   55 Kh As 5h 3c  7d Ks 4c
TM        857528312  5  4  f    -      -      -        -         1415    0    0 8c
TM        857528322  5  1 +Bk   k      k      f        -         1415   10    0 3c 2h 6s Qh
TM        857528360  5  4  f    -      -      -        -         1405    0    0 9c
TM        857528367  5  2  f    -      -      -        -         1405    0    0 9h
TM        857528392  6  1 +Bcc  c      f      -        -         1405   50    0 2s 8h Jc
TM        857528457  6  2  QQ   -      -      -        -         1355    0    0 Jd
TM        857528589  5  1 +Bk   kc    +kc    +kc      +bc        1355  100  130 5s 2s 2h 4c  6d Jc Ac
TM        857528658  5  3  c   +k      kc    +b       +b         1385   70   75 Th As 4h 7d  6d 8s 2d
TM        857528710  5  4  f    -      -      -        -         1390    0    0 Td
TM        857528751  5  4  c    k     +kc    +kc      +kf        1390   70    0 6c 3d 6s 5d
TM        857528815  5  1 +Bc   c     +kf     -        -         1320   30    0 3d 7h Jc
TM        857528876  5  1 +Br   -      -      -        -         1290   20   30 3d
TM        857528895  5  2  c   +k      f      -        -         1300   10    0 As 9c 7d
TM        857528925  5  3  ccc  ccc   +kc    +kc      +k         1290  140  215 Qh 8c 8s 6c  3d 5c 2d
TM        857529007  5  5  c   +k      c      c        c         1365   70  150 8s 8d Ah 7s  5d 7d 4d
TM        857529051  5  2  cc   c      c      c        k         1445   70    0 3d Qc 5s Jd  2d 9s Ah
TM        857529110  5  2  f    -      -      -        -         1375    0    0 6h
TM        857529158  5  4  c    -      -      -        -         1375   10   20 6h
TM        857529167  5  3  cc   c      c      c        k         1385   70  210 Qd 8s 6d Ac  Qh 7h 9d
TM        857529230  5  5  f    -      -      -        -         1525    0    0 9d
TM        857529244  5  3  c    c      cc     f        -         1525   70    0 6s Js 9d 5d
TM        857529314  5  2  f    -      QQ     -        -         1455    0    0 4c
TM        857591426  2  1 +BQ   -      -      -        -         1455   10   10 2h
TM        857613898  3  2  f    -      -      -        -         1455    0    0 Ts
TM        857613916  3  2  c   +k      c      c        f         1455   50    0 Ts Th 3h Jd
TM        857613951  4  2  cc  +kc    +bc    +kc      +krc       1405  170    0 Kh 8h Kd 6d  7s 5s 3s
TM        857614044  6  6  f    -      -      -        -         1235    0    0 Kc
TM        857614131  6  6  f    -      -      -        -         1235    0    0 Ks
TM        857614189  7  5  f    -      -      -        -         1235    0    0 5s
TM        857614266  7  7  f    -      -      -        -         1235    0    0 Jd
TM        857614399  6  3  f    -      -      -        -         1235    0    0 Td
TM        857614425  7  6  cc   cc    +kc    +b       +kc        1235  110  180 5c 3d 5d 4h  6s 9d 8h
TM        857614515  8  3  f    -      -      -        -         1305    0    0 9h
TM        857614604  8  4  cc   k      c      k        r         1305   80  230 6h 4d 9d Ks  8h 9h 9c
TM        857614708  8  7  f    -      -      -        -         1455    0    0 Jd
TM        857614749  7  4  f    -      -      -        -         1455    0    0 5s
TM        857614796  8  4  cc  +kc    +kc     c        f         1455   80    0 6c Ks 5c 8c
TM        857614865  8  2  cc   f      -      -        -         1375   30    0 Jd Tc
TM        857614974  8  2  f    -      -      -        -         1345    0    0 4h
TM        857615146  8  5  c   +kc     kf     -        -         1345   20    0 4d Jh Qs
TM        857615289  7  6  c    -      -      -        -         1325   10   20 5d
TM        857615371  6  2  QQ   -      -      -        -         1335    0    0 Jd
TM        857697351  4  4  f    -      -      -        -         1335    0    0 5c
TM        857697365  3  2  cc   rc     c      c        c         1335  110  125 6d 5s 8d 6s  2h Qh As
TM        857697419  3  2  f    -      -      -        -         1350    0    0 5c
TM        857697426  3  2  cc   c      c      c        r         1350  110  230 7d Jc 8h 2c  2d 8c 2h
TM        857697471  3  3  cc  +kc    +kc    +kc      +k         1470   70  160 9h Qc 4d 9c  Ad 4c Kc
TM        857697530  3  3  cc  +k     +k     +k       +k         1560   40  120 Jc Qh Ah Jd  Qd Ts Th
TM        857697591  2  1 +B    -      -      -        -         1640   10   10 3c
TM        857697594  2  1 +Bk   k      k      k        k         1640   10   10 7d 6d 8d Jh  6h Ts 2h
TM        857697640  3  2  fQ   -      -      -        -         1640    0    0 Kc
TM        857881162  5  5  c    k      k      c        c         1640   70    0 Tc Js 7d 2d  7s Th 8h
TM        857881225  5  1 +Bk   c     +kc    +kc      +bc        1570  100  140 3d Qd As Ks  4s 6h 5c
TM        857881317  6  5  f    -      -      -        -         1610    0    0 4s
TM        857881409  6  3  f    -      -      -        -         1610    0    0 Kc
TM        857881468  6  4  f    -      -      -        -         1610    0    0 Kh
TM        857881551  6  5  f    -      -      -        -         1610    0    0 9c
TM        857881606  6  3  cc   k      c      c        f         1610   60    0 7h Jd Ks 3d
TM        857881733  6  6  c    kc     c     +kf       -         1550   50    0 4c Th 2d Qs
TM        857881845  6  6  c    k      k      k        f         1500   10    0 7c 5h Kh Td
TM        857881925  7  2  c    k      cc     kf       -         1490   50    0 5d 7h Qc Kc
TM        857882010  6  5  f    -      -      -        -         1440    0    0 Qc
TM        857882039  7  6  f    -      -      -        -         1440    0    0 7s
TM        857882104  7  4  cc   c      f      -        -         1440   30    0 Jc 7d 9d
TM        857882256  7  6  f    -      -      -        -         1410    0    0 6d
TM        857882341  8  5  c    c      c      f        -         1410   40    0 5d Qc 7c 9d
TM        857882421  8  1 +Bc   c      r      rr       r         1370  190  560 2d 5c As 3h  7c 4s Kd
TM        857882560  8  6  f    -      -      -        -         1740    0    0 6h
TM        857882667  8  8  c    cc     c      kf       -         1740   60    0 5h 9d 6c Th
TM        857882804  8  6  f    -      -      QQ       -         1680    0    0 Tc
TM        858215336  7  6  f    -      -      -        -         1260    0    0 Qs
TM        858215412  8  6  cc   k      kf     -        -         1260   20    0 5c Jh 4c
TM        858215549  7  5  cc   c      c      c        k         1240   90  180 7d 8s 6c 9s  4s 2h 2c
TM        858215671  6  2  f    QQ     -      -        -         1330    0    0 Js
TM        858819614  5  5  cc   f      -      -        -         1330   30    0 Ts 6d
TM        858819657  4  1 +Bc   c     +kc    +kc      +kc        1300   90    0 Qd 4s Qh 6s  6c 8s 8d
TM        858819743  6  5  c    k      cf     -        -         1210   30    0 8d 4h 5s
TM        858819835  6  3  cc   ccc    bc     k        kQ        1180  100  180 6d 2c 7c 8h  5d 5h Jc
TM        858897364  4  4  f    -      -      -        -         1260    0    0 Jh
TM        858897375  4  2  c   +k     +k     +k       +k         1260   10    0 Qh Kd 9c 5s  8c Qc Ad
TM        858897427  4  4  c   +kc     c      f        -         1250   40    0 5s Jh Ks Qc
TM        858897486  4  1 +Bk   f      -      -        -         1210   10    0 5d Ks
TM        858897511  5  4  f    -      -      -        -         1200    0    0 5h
TM        858897587  6  4  Q    -      -      -        -         1200    0    0 9h
TM        859332304  5  3  f    -      -      -        -         1200    0    0 Tc
TM        859332334  5  5  f    -      -      -        -         1200    0    0 5c
TM        859332367  5  5  c    b      b      b        r         1200  100  200 8c 6c 2s 6d  Tc 4c 5c
TM        859332442  5  4  f    -      -      -        -         1300    0    0 8d
TM        859332517  6  5  f    -      -      -        -         1300    0    0 6c
TM        859332600  6  4  f    -      -      -        -         1300    0    0 Td
TM        859332665  6  3  cc  +k      c     +kc      +kf        1300   60    0 Qc 8c 4d 4h
TM        859332754  7  2  Q    -      -      -        -         1240    0    0 9h
TM        859338212  7  1 +Bf   -      -      -        -         1240   10    0 4s
TM        859338228  7  3  c    c      cf     -        QQ        1230   50    0 5h 4h 6s
TM        859414871  3  2  f    -      -      -        -         1180    0    0 Kc
TM        859414879  3  3  f    -      -      -        -         1180    0    0 8c
TM        859414885  4  2  cc  +kc    +kc    +k       +kf        1180   50    0 Ad 7h Ks Ah
TM        859414980  2  2  c   +kQ     -      -        -         1130   10   20 Th 7h
TM        859763149  3  1 +Bc   c      k      c        f         1140   50    0 5h 6h 9c Kh
TM        859763229  3  2  cc   c      c      c        k         1090   70    0 8s 2c 6s Td  4c Ts 9d
TM        859763314  3  1 +Bk   b     +b     +bc      +kf        1020   80    0 3h 6s 6d 9c
TM        859763384  3  2  c    c      c      f        -          940   40    0 9s 6d 2c Jc
TM        859763436  4  1 +Bk   c      f      -        -          900   20    0 2s Kc 3s
TM        859763550  4  4  f    -      -      -        -          880    0    0 7s
TM        859763713  5  3  c   +k     +kc     f        -          880   30    0 As 3s Qd 8d
TM        859763809  7  2  cc   c      c      c        c          850   90    0 5c 9d 4d 6h  5s 3d 4c
TM        859763931  7  4  c    k      k      c        Q          760   30    0 8d 9h Ad 2c
TM        859765130  5  4  rc   c      c      c        r          730  140  480 8s 5h Js Qs  Kc Ks As
TM        859765213  5  1 +Bf   -      -      -        -         1070   10    0 2s
TM        859765318  5  2  ccc  c      c      c        r         1060  150  270 Kc 3d Td Ad  5h 6h 2h
TM        859765449  5  3  cc   f      -      -        -         1180   20    0 5h Td
TM        859765513  4  1 +Bc   c      c      f        -         1160   50    0 5d 3d Qh 4d
TM        859765563  4  1 +Br   b      b      c        c         1110   90    0 5c 9d 4c 2c  Qh Jh Qd
TM        859765625  4  3  crc +kr    +bc    +kc      +kc        1020  140  200 As Kd 9c Td  6d 6c Ad
TM        859765719  4  4  cc  +k     +kc    +kc      +kf        1080   60    0 Jc Kc 8h 4s
TM        859765765  4  4  r    -      -      -        -         1020   20   30 Ad
TM        859765776  3  1 +Br  +kcc   +krr   +b       +b         1030  190  470 7d 7s 2s 6h  3s 5s 8s
TM        859765843  3  1 +Bc   rc     c     +kc      +brrc      1310  210  210 5h 2h 9s 2s  7c 6c 8h
TM        859765905  3  3  c   +k     +kc    +kc      +kc        1310   70    0 Ac 7s 8d Qs  4d Td 3d
TM        859765961  4  1 +Br  +k     +k     +b       +b         1240   60  100 7c Td 5c As
TM        859766005  4  3  cc   c      c      c        kf        1280   90    0 Jc 5c 2d Ks
TM        859766090  4  4  r    r      b      b        k         1190   80  170 Kd 5c Ad Qd  Ks 5s 6h
TM        859766150  4  2  r    c      c      k        rrc       1280  150  175 4c Th 7s Kc  6s 2d 5d
TM        859766278  4  3  r    rc     c      k        c         1305   90  125 Js 2d 6c Qd  7c Jd 7s
TM        859766315  4  3  f    -      -      -        -         1340    0    0 9d
TM        859766382  4  3  c    k      k     +b        -         1340   30   40 7s 2h 5d 7d
TM        859766471  4  3  rc   c      c      c        c         1350  100  280 Ks 8d 7d 9c  Kc Qc 8h
TM        859766541  4  3  c    -      -      -        -         1530   10   20 As
TM        859766563  3  3  c   +k     +kc    +kc      +kc        1540   70  140 7d Kd Ts 5c  Ad 7s As
TM        859766603  3  3  c    k     +k     +k       +kc        1610   30    0 8s Jc Kh Qh  3c Ah 6c
TM        859766656  3  1 +B    -      -      -        -         1580   10   10 6h
TM        859766680  3  3  cc  +k     +k     +b       +b         1580   60  120 Ac Qc 8c 7c  3h 2c 5d
TM        859766718  3  1 +B    -      -      -        -         1640   10   10 3h
TM        859766725  3  3  cc   c      k      b        -         1640   50   80 5h 8h 7d Jh
TM        859766752  3  2  ccc  kc     c     +kc      +kf        1670   90    0 7c 5d 9s As
TM        859766805  3  1 +Bf   -      -      -        -         1580   10    0 8h
TM        859766822  3  3  c    rr     c      c        c         1570  120    0 5d 8d Js 4h  6d 9d 4s
TM        859766852  3  2  f    -      Q      -        -         1450    0    0 9h
