Eh        898387914  5  2  c   +k     +kc     c        b         1000   70   70 Kh 6d 5c 7s  Kc Jc Kd
Eh        898387961  5  1 +Bk   k     +b     +k       +b         1000   50  110 3c Qc Qh Ac  Kc Kh 2c
Eh        898388009  5  3  c    k     +kc     kc       b         1060   70  170 2s Qh 7h 3c
Eh        898388088  5  5  f    -      -      -        -         1160    0    0 5h
Eh        898388157  5  5  c    k      k      k        f         1160   10    0 4h Jh Qh 6h
Eh        898388223  5  5  c    kc     k      kc       kf        1150   40    0 7s Qs 9c Jc
Eh        898388336  5  1 +Bk   k      k      b        k         1110   30   50 2c 9c 4s 7c  6c 6d Jc
Eh        898388412  5  2  c   +k     +kc    +k       +k         1130   30    0 Kh 3c 6d 4s  5c Tc Qc
Eh        898388467  6  2  fQQ  -      -      -        -         1100    0    0 Qc
