GOD       936447889  4  1 +Bc   cc    +kcc   +kc      +k          490  160    0 7c 9d Ac 5c  3c 3d Qd
GOD       936447964  5  2  r   +b      b      b        b          330   90  160 Ad 3c 8c Kd
GOD       936448010  5  4  r   +b      -      -        -          400   30   60 Tc Ks
GOD       936448027  5  3  c   +kc    +kc    +kf       -          430   40    0 Jc 4d Ah 9s
GOD       936448075  4  3  f    -      -      -        -          390    0    0 9s
GOD       936448111  4  3  c   +k      k      f        -          390   10    0 9h Ts Qs Ac
GOD       936448152  4  3  cc   kc     k      k        c          380   50    0 Td 3s 4d 8h  Ks Jh Jd
GOD       936448203  3  1 +Bc   c      c      c        c          330   90    0 2h 4h Td 7c  7d 9c 5h
GOD       936448227  2  2  r    -      -      -        -          240   20   30 Ts
GOD       936448236  2  1 +B    -      -      -        -          250   10   10 8d
GOD       936448240  2  2  r    -      -      -        -          250   20   30 As
GOD       936448244  2  1 +B    -      -      -        -          260   10   10 5h
GOD       936448248  2  2  r    -      -      -        -          260   20   30 Qh
GOD       936448252  2  1 +B    -      -      -        -          270   10   10 2s
GOD       936448256  2  1 +Brr  c      c      c        b          270  110    0 4c Jd 6h 5c  9c Ac Th
GOD       936448288  2  2  cc  +b     +b      -        -          160   50   80 Kd 2s 9d
GOD       936448311  2  1 +Bc   c      c      c        b          190   90    0 6s 4d 8d 2s  4s Js 7c
GOD       936448339  2  1 +Bc   r      b      b        -          100   80  140 6h 3s 2h Ac
GOD       936448375  2  1 +Br   k     +b     +bc      +kc         160  110    0 5h 9d Qs Qc  Ks Ad Qd
GOD       936448414  2  1 +B    -      -      -        -           50   10   10 Jd
GOD       936448419  2  1 +Bc   c     +bA     -        -           50   50  100 5c 6c 6h  9c Jc 9h 7h
GOD       936448436  2  1 +Br   b      b     +b       +bA         100  100  200 Jc Tc Qs Qc  Kc Js 9h
GOD       936448468  2  2  f    -      -      -        -          200    0    0 Ks
GOD       936448476  2  1 +B    -      -      -        -          200   10   10 3s
GOD       936448481  2  1 +B    -      -      -        -          200   10   10 6c
GOD       936448483  2  2  c   +k      k      k        f          200   10    0 Ts 9c 5s 7s
GOD       936448518  2  2  c   +k     +b      -        -          190   30   40 8d 4s Qh
GOD       936448538  2  1 +B    -      -      -        -          200   10   10 6d
GOD       936448541  2  1 +B    -      -      -        -          200   10   10 4h
GOD       936448544  2  2  f    -      -      -        -          200    0    0 Qs
GOD       936448550  2  2  f    -      -      -        -          200    0    0 Kc
GOD       936448553  2  2  f    -      -      -        -          200    0    0 Js
GOD       936448559  2  1 +B    -      -      -        -          200   10   10 4h
GOD       936448562  2  2  c   +b     +k     +kc      +b          200   60  100 7h Jd Ts 8h
GOD       936448606  2  2  r    -      -      -        -          240   20   30 8c
GOD       936448612  2  1 +Bf   -      -      -        -          250   10    0 Ks
GOD       936448624  2  2  r    -      -      -        -          240   20   30 Kh
GOD       936448628  2  2  f    -      -      -        -          250    0    0 8s
GOD       936448635  2  1 +B    -      -      -        -          250   10   10 8d
GOD       936448638  2  2  r   +b     +b     +b       +b          250   90   90 Ac Ah 7d 4d  2c 8c Tc
GOD       936448670  2  1 +B    -      -      -        -          250   10   10 Td
GOD       936448677  2  1 +B    -      -      -        -          250   10   10 2h
GOD       936448680  2  2  c   +bc    +k     +kc      +kf         250   50    0 4s Qd 7s Ah
GOD       936448716  2  1 +Br   b      b     +b       +b          200  100  180 2s Jd Tc Js
GOD       936448747  2  1 +B    -      -      -        -          280   10   10 Kc
GOD       936609406  7  7  c    k      c     +k       +kf         280   30    0 9s Tc Ah Qh
GOD       936609482  7  1 +Br   b      b      b        b          250   90  270 2s 8h 2d Kh  As 2c 8d
GOD       936609592  7  1 +Bc   c      rr     c        rc         430  190    0 3h 8s 2c Ks  7h Qh As
GOD       936609670  7  4  f    -      -      -        -          240    0    0 Kh
GOD       936609731  7  4  f    -      -      -        -          240    0    0 Qh
GOD       936609810  7  5  rr   kcc    ccc    f        -          240  160    0 4h Jd 8s 7s
GOD       936609999  7  7  r    rr     cA     -        -           80   80    0 Tc 8h 2s Kc  As Jc 4c
GOD       936610242  7  5  c    k     +b     +b       +b         1000   70  180 Jd 9c 9s Ah
GOD       936610286  7  7  f    -      -      -        -         1110    0    0 7h
GOD       936610380  7  7  c    k      b     +bc      +kc        1110   90    0 3c 5s 2d 5d  Ac Ad 9h
GOD       936610437  7  3  f    -      -      -        -         1020    0    0 Td
GOD       936610512  7  3  f    -      -      -        -         1020    0    0 6c
GOD       936610632  7  5  f    Q      -      -        -         1020    0    0 6h
