Mo        813270457  2  2  c   +kc    +kc    +f        -         1000   40    0 9s 7c Qs Ah
Mo        813270523  2  2  c   +k     +k      k        k          960   10   20 8c As 5s 7s  Jd 8s Kd
Mo        813270568  3  1 +Bk  +kc    +kf     -        -          970   20    0 2h Ks Th
Mo        813270611  3  1 +Bk   b      -      -        -          950   20   30 4d 3s
Mo        813270642  3  1 +B    -      -      -        -          960   10   10 4d
Mo        813270652  4  2  cc  +kc    +kc    +kc      +k          960   70    0 6c 6h Tc Ac  7s 9d 4h
Mo        813270709  4  4  cc  +kr    +k     +k       +kr         890   90    0 Ah 4h Kh 8s  Tc 4s As
Mo        813270842  4  3  f    -      -      -        -          800    0    0 Kd
Mo        813270890  4  2  f    -      -      -        -          800    0    0 Jd
Mo        813270915  4  3  c    k      c      c        b          800   70  170 Td 5d Jc Ad
Mo        813271005  4  3  cc   c      c      c        k          900   70    0 Ad Qh 2h Js  Jd 5d Th
Mo        813271108  5  2  Q    -      -      -        -          830    0    0 7h
Mo        813271245  4  1 +Bcc  c      f      -        -          830   50    0 4c Td Qd
Mo        813271320  5  3  c    c      f      -        -          780   30    0 9h 7d Qs
Mo        813271396  5  2  cc  +kc    +kf     -        -          750   30    0 7h Kc Ts
Mo        813271427  4  2  f    -      -      -        -          720    0    0 9s
Mo        813271441  4  4  cc  +kc    +k      c        k          720   50    0 8s 9c Ad Qd  Kc Ts Qc
Mo        813271515  4  3  f    -      -      -        -          670    0    0 Jc
Mo        813271568  4  4  f    -      -      -        -          670    0    0 8h
Mo        813271601  4  3  f    -      -      -        -          670    0    0 Ts
Mo        813271626  4  3  f    -      -      -        -          670    0    0 3s
Mo        813271677  4  4  cc   c      c      c        k          670   90  290 7s 8d 5d 9h  Jh 8c 6s
Mo        813271768  3  3  c    -      -      -        -          870   10   20 Qd
Mo        813271780  3  3  c   +k      k      k        k          880   10    0 9h Jd 8d 7s  6d Ah Qd
Mo        813271825  4  3  f    -      -      -        -          870    0    0 Kd
Mo        813271872  4  1 +BQ   -      -      -        -          870   10    0 4s
Mo        813271982  5  3  c   +k     +k     +k       +k          860   10   30 Jc 4h Ks 2d  5d 7h Jh
Mo        813272028  5  2  c   +b     +k      c        f          880   40    0 Qs Qc 3h 9c
Mo        813272110  5  5  f    -      -      -        -          840    0    0 Ah
Mo        813272149  5  2  c    c      k      k        r          840   60   70 Td 9c Js Jc  7s 8h 6h
Mo        813272216  6  4  f    -      -      -        -          850    0    0 Tc
Mo        813272335  4  4  cc   c      kc     k        k          850   50    0 Tc 7h 7s 9s  Jc Kc 3d
Mo        813272407  4  1 +Bk   c      c     +b       +b          800   80   90 5h 2c 6c Ac  3s Tc 2h
Mo        813272451  4  1 +Bf   -      -      -        -          810   10    0 3c
Mo        813272518  5  3  cc   c      c      b        k          800   70   75 9c 7c 8c Td  Kh Ad Jc
Mo        813272558  5  5  f    -      -      -        -          805    0    0 Kh
Mo        813272613  5  2  c    k      c      c        r          805   90   90 Tc 9c Js Qs  Qc Jc Ah
Mo        813272677  5  4  f    -      -      -        -          805    0    0 Jc
Mo        813272725  5  1 +Bc   cc     c      k        b          805   90  270 2s 6d 2h 3h  7d 7c 7h
Mo        813272814  5  2  c   +k      f      -        -          985   10    0 4s Th 2h
Mo        813272887  5  5  f    -      -      -        -          975    0    0 9c
Mo        813272909  5  3  cc   c      cc     c        c          975  150    0 4s 6d 7d Jh  5h Qd As
Mo        813272995  5  1 +Bf   -      -      -        -          825   10    0 2d
Mo        813273026  5  3  cc   k      c      cc       cc         815  180    0 3s 8d Th 4d  Kd 6c 5d
Mo        813273139  6  5  c    k      k     +b       +kc         635   50    0 4s 7s 6d Ah  Ad Jc 8d
Mo        813273234  5  3  c   +k     +kc    +k       +kc         585   50   55 Qc 5c 9c Ts  7s Tc 9h
Mo        813273292  5  3  c   +b      b      -        -          590   40   60 7c 5c 8s
Mo        813273338  4  2  f    -      -      -        -          610    0    0 Qh
Mo        813273362  4  1 +Bc   c      k      k        b          610   50  100 4c 5h 6h 9h  Qh Qs Qc
Mo        813273416  4  1 +Bc   c      c      c        k          660   70   70 3h 8d 7c 2h  3s 6s Td
Mo        813273485  5  2  f    -      -      -        -          660    0    0 9d
Mo        813273541  6  2  c    k      f      -        -          660   10    0 Jc 2s 4s
Mo        813273629  6  4  cc   c      c     +kc      +kc         650  100    0 7d 8s 6s 8d  Kd 9d 2c
Mo        813273783  6  6  c   +k      k      f        -          550   10    0 7s Kc 6s 3c
Mo        813273850  7  5  c    f      Q      -        -          540   20    0 Ks 3s
Mo        813344974  5  5  c    k      k      k        c          520   30   70 Jc Th 3d 5c  8d 9s 5s
Mo        813345058  4  2  c    c     +kf     -        -          560   20    0 2s Jh Ad
Mo        813345139  4  4  f    -      -      -        -          540    0    0 Jc
Mo        813345190  4  4  c    c      f      -        -          540   30    0 Ts 6h 2d
Mo        813345282  4  4  c    k     +bc    +kc      +kc         510   90  180 6s Ac 6c Ks  7h As 3d
Mo        813345340  3  1 +Bc   c      c      r        k          600   90  180 9c 5h Ts 8h  5c Qh Js
Mo        813345411  4  3  f    -      -      -        -          690    0    0 Qd
Mo        813345432  4  3  f    -      -      -        -          690    0    0 Ks
Mo        813345448  4  1 +Bk  +k     +k     +k       +k          690   10   20 5h Jh Js As  Ts 8s 2h
Mo        813345493  4  2  f    -      -      -        -          700    0    0 Qd
Mo        813345507  4  3  c    c      f      -        -          700   20    0 5d Ts 8h
Mo        813345554  4  1 +Bk   c      k      k        k          680   20   25 5d 8c 2c 3h  Kc 7s Js
Mo        813345643  4  4  c   +k     +kf     -        -          685   10    0 Jc 5c 4h
Mo        813345698  4  4  c   +k      k      k        b          675   30   50 Ks 7h 5d 4d
Mo        813345825  4  3  f    -      -      -        -          695    0    0 Jc
Mo        813345837  4  3  cc  +kc    +kr    +k       +b          695   90  190 Jh Jc 5s 7s  8s Js As
Mo        813345942  5  5  f    -      -      -        -          795    0    0 9s
Mo        813346061  6  4  c   +kc    +k     +kc      +kc         795   80    0 Ks As Kd 8s  Th Jc 8h
Mo        813346204  7  3  f    -      -      -        -          715    0    0 7h
Mo        813346398  8  8  f    -      -      -        -          715    0    0 2s
Mo        813346476  8  7  c    kc    +kc     f        -          715   40    0 Ah 5s Qd 3h
Mo        813346676  7  7  c   +k     +kc    +kf       -          675   30    0 Js 2s 2h 6c
Mo        813346813  8  8  c    k      k      kf       -          645   10    0 6h 8s 3h 2s
Mo        813347000  8  8  c    c      c     +k       +kc         635   70    0 9c Ah 4d As  2d 2s 6s
Mo        813347162  8  1 +Bk  +kc     c     +kc      +k          565   60    0 5c 9h 3h Th  8s Ks Ah
Mo        813347405  6  4  f    -      -      -        -          505    0    0 4h
Mo        813347455  6  1 +Bk   k      c      c       +b          505  110  190 4s 5d 5c Jc  Qc Qs Qd
Mo        813347601  7  1 +Bc   c      f      -        -          585   30    0 2s Kd Qh
Mo        813347723  7  5  c   +kc    +kf     -        -          555   20    0 Qh 9d 5s
Mo        813347784  7  1 +Bk   k     +k      k        kr         535   50    0 4s 7d 4h 3d  3c Js 2c
Mo        813347927  6  1 +Bc   c      f      -        -          485   30    0 3d Kc Qd
Mo        813348014  5  5  f    -      -      -        -          455    0    0 6s
Mo        813348035  5  4  c    k      k      f        -          455   10    0 7d Js 8c 4d
Mo        813348162  5  2  c   +k      c      c        c          445   70   70 8s 9s 7h 3c  Ad 4c 7d
Mo        813348250  6  1 +Bk  +kc     f      -        -          445   20    0 2h Kh 7c
Mo        813348295  6  3  f    -      -      -        -          425    0    0 9c
Mo        813348511  7  4  Q    -      -      -        -          425    0    0 Td
Mo        813348626  7  6  c    k     +b     +b       +b          425   70   75 Qd 7c 7d Js  7s Jd 5c
Mo        813348707  7  6  f    -      -      -        -          430    0    0 Ad
Mo        813348824  7  1 +Bk   c      kc     c        c          430   80    0 3s 6c Kd Jd  3h 5d Kc
Mo        813348969  6  3  c   +k      k      k        k          350   10    0 Th Jh 8d 9d  5d 4h Jc
Mo        813349056  6  2  c    c      c      c        c          340   80  105 7h 3c Td 5s  Ac 6s Th
Mo        813349144  5  2  cc   c      k      b        -          365   50  100 7h 6s 4s 3s
Mo        813349239  5  3  f    -      -      -        -          415    0    0 Ac
Mo        813349258  5  5  c   +k      k     +k       +k          415   10   20 8s 6s Tc 6h  4h 5s Qd
Mo        813349333  5  1 +Bc   c      c      c        c          425   90  180 2d Th Qh 8s  8h 6c 4h
Mo        813349414  5  1 +Bk   b      -      -        -          515   20   30 6c 2d
Mo        813349470  5  3  c    k      c      b        -          525   50   80 5d 9d 6s 8c
Mo        813349511  4  3  f    -      -      -        -          555    0    0 Kd
Mo        813349524  5  1 +Bc  +bc     c      f        -          555   60    0 6c 6d 2h Kc
Mo        813349629  4  2  cc   c      f      -        -          495   30    0 Kh Tc Qd
Mo        813349680  4  2  c   +kc    +b     +b       +b          465   80  140 Tc 7h Td 7s
Mo        813349726  4  4  c    f      -      -        -          525   20    0 8h Qs
Mo        813349859  5  3  Q    -      -      -        -          505    0    0 Th
Mo        813430936  3  2  c    c      f      -        -          505   20    0 Td Kc 7h
Mo        813430985  3  1 +B    -      -      -        -          485   10   10 3d
Mo        813430992  3  1 +B    -      -      -        -          485   10   10 3s
Mo        813430999  3  2  c   +kc     c      c        c          485   90    0 Ah Tc 5d 3d  Js 7d 4s
Mo        813431073  3  2  c    c      c      cc       f          395   80    0 3s 8h 5c 4c
Mo        813431196  4  2  f    -      -      -        -          315    0    0 Ac
Mo        813431214  4  4  c    f      -      -        -          315   10    0 9h Qc
Mo        813431263  6  4  c    k      k      k        f          305   10    0 6h Js 5s Kc
Mo        813431365  5  2  c   +k     +bc    +kc      +k          295   70    0 Ah Ad 9d 7c  3c Th Qc
Mo        813431465  5  2  f    -      -      -        -          225    0    0 Th
Mo        813431595  5  2  c    c      k      f        -          225   20    0 Jd 2s 9s 4d
Mo        813431775  6  3  f    -      -      -        -          205    0    0 Kd
Mo        813431814  6  2  f    -      -      -        -          205    0    0 Js
Mo        813431974  6  2  c    c     +bc    +kc      +bc         205  120  320 7d 3h 3d 4c  5d Ad Jd
Mo        813432104  6  3  f    -      -      -        -          405    0    0 Td
Mo        813432231  5  4  cc   c      f      -        -          405   30    0 Th Qh 4s
Mo        813432412  5  3  f    -      -      -        -          375    0    0 6d
Mo        813432528  5  5  c    c      c     +k       +kc         375   80  120 5c 4s Kd Kc  8c Ad 6h
Mo        813432622  4  4  c   +kf     -      -        -          415   10    0 Qh 5c
Mo        813432689  5  2  cc  +bc    +kc    +kf       -          405   60    0 8c 8h Ah Kd
Mo        813432830  5  1 +Bk  +k     +kc    +k       +k          345   30   80 3c 3d 9s 9d
Mo        813432918  5  3  f    -      -      -        -          395    0    0 6h
Mo        813433018  6  4  c    c      c     +b       +bc         395  110    0 Js 6c 5h Jd  9h Jh Qc
Mo        813433140  6  1 +Bk  +k      b      b        k          285   50  150 2d 2s Kc Ad  8d 3h Kh
Mo        813433262  6  1 +Bk   k      c     +b       +b          385   70  200 2c 9h Js 9d  Jh Jd 8c
Mo        813433375  7  1 +Bk   k      f      -        -          515   10    0 3s 7h Qs
Mo        813433496  7  6  f    -      -      -        -          505    0    0 9c
Mo        813433636  7  6  cc   c      f      -        -          505   50    0 Jd 7c 3c
Mo        813433767  8  8  f    -      -      -        -          455    0    0 3h
Mo        813433947  6  5  f    -      -      -        -          455    0    0 8c
Mo        813433965  6  5  f    -      -      -        -          455    0    0 5s
Mo        813434043  8  8  c    c      f      -        -          455   30    0 9d 4d Qh
Mo        813434110  6  2  f    -      -      -        -          425    0    0 Tc
Mo        813434190  7  4  f    -      -      -        -          425    0    0 Jh
Mo        813434261  7  2  cc   c      c     +kc      +kf         425   90    0 3d Qc 5d 3h
Mo        813434524  8  6  c    kc     k      k        f          335   20    0 2d 8h 6d Tc
Mo        813434695  7  5  c    c      c      c        c          315   90  210 Qs 4h Ks 6h  Jh Th 7h
Mo        813434779  7  2  f    -      Q      -        -          435    0    0 4d
Mo        813518081  3  2  f    -      -      -        -          435    0    0 Th
Mo        813518094  3  2  c    k     +k      c        c          435   50   75 8c 7c Qd Ts  2d 8h Th
Mo        813518153  3  2  c    b      c      c        k          460   60   70 6d 5h Kh Qd  Ad 6s Th
Mo        813518252  3  2  c   +k      f      -        -          470   10    0 Ah 2c 9c
Mo        813518305  3  3  c    b     +k      k        c          460   40    0 4h 2s Qc 4c  6h Ac 2c
Mo        813518430  3  1 +Bk   k      k      k        k          420   10   15 3s 5d 6h 2s  Kh Ks 6s
Mo        813518501  3  2  c    c      k      c        k          425   40  120 8h 5d 4s 2h  Ad 2s 4h
Mo        813518625  4  1 +Bk   k      k      k        k          505   10   20 5s 7d 8c Qc  4c 5c 3c
Mo        813518712  4  3  c   +k      f      -        -          515   10    0 Ac 9h 2d
Mo        813518798  5  4  f    -      -      -        -          505    0    0 8s
Mo        813518899  5  4  c   +k      kf     -        -          505   10    0 7c Kd Js
Mo        813519027  5  1 +Bc   k     +b      c        r          495  110  300 7d 5s 7s 4h  7h Jc 4c
Mo        813519159  7  6  c    cc     k      kc       kf         685   60    0 8c Qc 9c Tc
Mo        813519366  6  5  f    -      -      -        -          625    0    0 Jc
Mo        813519416  7  2  cf   -      -      -        -          625   10    0 9d
Mo        813519528  7  4  f    -      -      -        -          615    0    0 Jh
Mo        813519595  7  4  f    -      -      -        -          615    0    0 Qc
Mo        813519679  7  7  f    -      -      -        -          615    0    0 7c
Mo        813519809  6  3  f    -      -      -        -          615    0    0 Th
Mo        813519888  7  1 +Bk   c      f      -        -          615   20    0 3s Tc 6h
Mo        813519938  7  6  f    -      -      -        -          595    0    0 Ts
Mo        813520081  7  5  c    kc     kc     cc       c          595  120  200 8h 3d 2s 8d  Ah 4c 2c
Mo        813520236  7  4  cc  +kc    +k     +k       +k          675   30   35 Ad 4d 7d 2c  2d 3c Jc
Mo        813520310  6  1 +Bk   k      k     +kf       -          680   10    0 4c 8h 3h 8s
Mo        813520412  5  1 +Bk   k      k      c        k          670   30    0 2d 8c 3s 7h  3d Qh 8d
Mo        813520469  5  3  c   +kc    +kc    +kc      +k          640   60   70 4d Ah Js 8h  7d 2h Kd
Mo        813520556  5  4  fQ   -      -      -        -          650    0    0 7h
Mo        813959277  4  1 +Bc   kc     c      c        c          650   90    0 2h 8s 4c 3c  Jh Td Ah
Mo        813959345  4  3  c    k      c      c        c          560   70    0 7h 5c Ac 3c  Th Qd 5h
Mo        813959430  5  1 +Bk   cc     kc    +k       +b          490   70  210 3c 6d 2h 2d  2c Qc Js
Mo        813959542  4  4  f    -      -      -        -          630    0    0 4c
Mo        813959572  3  3  f    -      -      -        -          630    0    0 Jc
Mo        813959587  2  1 +Bf   -      -      -        -          630   10    0 3c
Mo        813959598  2  2  f    -      -      -        -          620    0    0 8s
Mo        813959611  2  2  c   +k     +k      f        -          620   10    0 As Js 7d Th
Mo        813959636  2  2  f    -      -      -        -          610    0    0 9d
Mo        813959651  2  1 +B    -      -      -        -          610   10   10 Qc
Mo        813959666  2  1 +B    -      -      -        -          610   10   10 2d
Mo        813959669  2  2  f    -      -      -        -          610    0    0 Kh
Mo        813959680  2  2  c   +bc    +k     +k       +kc         610   50   50 8s Ts 9h Qs  8h Kc 5s
Mo        813959720  3  2  cc   c      c      c        c          610   90  180 9h Ks 6d 2c  2s 9d 6s
Mo        813959758  3  1 +Bc   c      c      b        b          700   90  180 3d 6d Jd 5c  Ks 2d Qd
Mo        813959822  3  1 +B    -      -      -        -          790   10   10 3c
Mo        813959843  3  1 +Bc  +kc    +bc    +k       +k          790   70  160 6c 6d 4h 8s  4s 8h 5s
Mo        813959892  3  2  f    -      -      -        -          880    0    0 4d
Mo        813959909  3  2  f    -      -      -        -          880    0    0 4d
Mo        813959915  3  3  f    -      -      -        -          880    0    0 9c
Mo        813959933  3  1 +Bc   f      -      -        -          880   20    0 2s 9d
Mo        813959971  3  1 +Bk  +bc    +k     +k       +k          860   30   60 Jc Qs 2s As  Qh 6h 8d
Mo        813960023  3  3  f    -      -      -        -          890    0    0 Tc
Mo        813960035  4  3  f    -      -      -        -          890    0    0 Td
Mo        813960072  4  3  f    -      -      -        -          890    0    0 Qc
Mo        813960088  4  2  cc  +kc    +kc    +kc      +b          890   90  190 Ad 7c Js 8h  2d 2s 2h
Mo        813960155  5  4  c    k      k      k        c          990   30   35 3s 5s 8d Kd  Ah 5c 6h
Mo        813960243  5  3  f    -      -      -        -          995    0    0 7c
Mo        813960315  5  5  f    -      -      -        -          995    0    0 Jh
Mo        813960372  5  2  cc  +k     +k      c        c          995   60   80 Ah Ts 4s Jh  6h Ad 3s
Mo        813960456  4  2  c   +k     +k     +k       +kc        1015   30    0 Ad 4c 7c 9d  5h 4s Jd
Mo        813960510  5  2  c    c      c      f        -          985   40    0 4s Qc 9c 8s
Mo        813960578  5  1 +B    -      -      -        -          945   10   10 4h
Mo        813960594  5  4  c    c      c      c        c          945   90    0 Jd 2d 4s Ts  Qc Kd Js
Mo        813960664  5  5  f    -      -      -        -          855    0    0 Td
Mo        813960711  5  2  cc   f      -      -        -          855   20    0 8s 9d
Mo        813960774  5  5  f    -      -      -        -          835    0    0 7s
Mo        813960792  5  4  c   +kc    +kc     c        r          835  100  200 5d Td 8h 2c  3c Ad 4s
Mo        813960857  4  4  f    -      -      -        -          935    0    0 6c
Mo        813960876  4  3  f    -      -      -        -          935    0    0 3s
Mo        813960884  4  4  f    -      -      -        -          935    0    0 Td
Mo        813960941  4  4  f    -      -      -        -          935    0    0 Th
Mo        813960961  4  3  c   +k     +k     +b       +b          935   50   80 8d Qd 6h 2s
Mo        813961016  4  2  c    kc    +kc     c        b          965   80  220 7h Kh As 3c  Qh 7s 7d
Mo        813961081  4  4  c    c     +kc    +kc      +k         1105   60    0 5d 4h Qd 5s  6h Kh 7s
Mo        813961143  4  4  cc  +kc    +kc     c        c         1045   90    0 7s Ad Th 6d  7h 9c 8s
Mo        813961234  4  1 +Bk   k     +b     +kc      +k          955   50   50 2d 6c 6s 8d  Jd Kd As
Mo        813961279  4  3  c    c     +kc    +kf       -          955   40    0 6s Qd Jd 9s
Mo        813961341  4  4  f    -      -      -        -          915    0    0 8h
Mo        813961410  4  3  f    -      -      -        -          915    0    0 8d
Mo        813961437  4  2  cc   kc     kf     -        -          915   40    0 9s 3h Th
Mo        813961500  4  1 +B    -      -      -        -          875   10   10 2c
Mo        813961507  4  1 +Bc  +kc     kc    +k       +k          875   50   65 4c Jc 8c 7c  6h As 9d
Mo        813961592  4  1 +Bc   f      -      -        -          890   20    0 3s Kc
Mo        813961662  4  3  f    -      -      -        -          870    0    0 4h
Mo        813961716  3  3  f    -      -      -        -          870    0    0 As
Mo        813961771  3  2  Q    -      -      -        -          870    0    0 9c
Mo        815078500  5  5  f    -      -      -        -          870    0    0 Ts
Mo        815078608  5  2  cc  +kc    +kc     c        cc         870  170    0 Kh 6h 3h Jc  6d 5d Js
Mo        815078770  6  2  cc  +krc   +kc    +k       +k          700   80  120 5s Ad Kc Js  Jd 3d Qc
Mo        815078886  6  6  crc +kc    +k     +k       +b          740   70  340 4c As 6h 3d  7h 8c 8d
Mo        815079063  6  1 +Bk  +kf     -      -        -         1010   10    0 2h 2d
Mo        815079237  6  4  c    k      k      f        -         1000   10    0 7d 2h 2s 3h
Mo        815079421  6  5  f    -      -      -        -          990    0    0 8c
Mo        815079535  6  5  f    -      -      -        -          990    0    0 4d
Mo        815079631  6  5  f    -      -      -        -          990    0    0 7h
Mo        815079738  7  4  ccc  r      brrr   rrc      rc         990  370  480 4c 8s 5d 4s  2s As 9c
Mo        815080043  7  5  cc   rc     cc     kc       k         1100  160    0 8c 2d 9s Js  7s 8h 5d
Mo        815080219  8  4  Q    -      -      -        -          940    0    0 Td
Mo        815165924  7  6  f    -      -      -        -          940    0    0 9s
Mo        815166045  7  3  c   +k     +kc    +kc      +k          940   50  150 Kd Ah 5d 3s  8h 7c Ks
Mo        815166132  6  6  c   +k     +k      k        f         1040   10    0 Qs 3h Kh Td
Mo        815166201  6  2  cc  +kc    +kf     -        -         1030   30    0 7d 7c Ks
Mo        815166306  6  5  f    -      -      -        -         1000    0    0 8s
Mo        815166356  6  1 +Bf   -      -      -        -         1000   10    0 2d
Mo        815166435  6  6  f    -      -      -        -          990    0    0 5h
Mo        815166539  6  3  f    -      -      -        -          990    0    0 Jc
Mo        815166641  6  1 +Bf   -      -      -        -          990   10    0 6s
Mo        815166758  7  3  cc  +kc    +bc    +k       +kc         980   90    0 5h Ac 2h 3c  8d Qs 7c
Mo        815166874  7  7  c   +k     +kc    +kc      +k          890   50  100 Qc Jc As 3c  2d Js 6s
Mo        815166994  8  6  c    k      k      c        c          940   70  115 Qd Th 2s Tc  5h Td 8d
Mo        815167187  7  1 +Bk   f      -      -        -          985   10    0 3d Th
Mo        815167313  8  4  cc  +kf     -      -        -          975   20    0 3h Qd
Mo        815167483  6  2  c    c      k      k        k          955   20    0 7c 4h 5h Jd  Tc 3c 5s
Mo        815167600  4  1 +Bk  +kc    +kc    +kc      +kc         935   80    0 4c Qh 7d 8h  7c 9d 9c
Mo        815167653  5  4  f    -      -      -        -          855    0    0 Jc
Mo        815167748  4  1 +Bk   c      f      -        -          855   20    0 2s Qh 4s
Mo        815167801  5  1 +Bc   cc     k      c        k          835   60    0 3c Kd 4d 6d  4s 6c 7s
Mo        815167908  5  1 +Bc  +kcc   +k     +kc      +kc         775   90    0 2d 2h 9c 3c  7d 3s 5h
Mo        815168071  5  2  fQ   -      -      -        -          685    0    0 Jc
