Rex       936230165  7  4  c    rc     c      k        cc        1000  110    0 9d 8d Qh 9c  2d 5d 7c
Rex       936230271  7  5  f    -      -      -        -          890    0    0 Kh
Rex       936230351  7  5  c   +k     +kf     -        -          890   10    0 Qd 9c Qh
Rex       936230402  7  4  c   +kc    +kcc   +kc      +kc         880  140  510 7c 7h 3c 6c  As 9d 2h
Rex       936230559  7  1 +Bc   cc     cc     ccc      c         1250  270    0 2h 3s 2s 4h  8h 3d 2d
Rex       936230790  8  2  c    kf     Q      -        -          980   10    0 Qs 5c
