mrC       797558728  8  5  c   +krc   +kc     c        k         1000   80    0 Kc 9c 6s Js  8h 7c 7s
mrC       797558802  8  2  f    -      -      -        -          920    0    0 5h
mrC       797558885  8  2  cc   rc     r      rf       -          920  130    0 Kh Jh Ah 4c
mrC       797558998  8  6  f    -      -      -        -          790    0    0 Qh
mrC       797559080  8  8  c    cc     c      f        -          790   60    0 9d 7c Qd Ks
mrC       797559165  8  5  cc   c      c      b        b          730   90  260 9c Th 7s 6h
mrC       797559253  7  3  c    f      -      -        -          900   10    0 Jh 5s
mrC       797559288  7  6  c    c      k      f        -          890   20    0 Qc 2d 4h 3c
mrC       797559346  7  2  c    kc     rc     cc       f          870  140    0 6c 2h 4h 8s
mrC       797559568  7  2  Q    -      -      -        -          730    0    0 3h
mrC       797819552  5  3  c   +kc     f      -        -          730   40    0 5s Ah 9s
mrC       797819657  5  4  f    -      -      -        -          690    0    0 9c
mrC       797819710  5  4  c    r     +kc    +bcc     +kf         690  130    0 Jc Td Ac 5d
mrC       797819841  5  1 +Bc  +kc    +b      -        -          560   50   80 4h Ad 3c
mrC       797819908  6  3  f    -      -      -        -          590    0    0 3c
mrC       797820006  5  1 +Bc   rc     f      -        -          590   50    0 3s 5c Jh
mrC       797820104  5  1 +Bc   f      -      -        -          540   20    0 3s 8s
mrC       797820146  5  3  c   +b     +bc    +br      +b          520  140  150 5h 5c 4c 3c  Ks Ad 8d
mrC       797820211  5  4  f    -      -      -        -          530    0    0 8c
mrC       797820291  5  4  cf   -      -      -        -          530   10    0 Kd
mrC       797820494  6  6  c    c      c     +kf       -          520   40    0 6c 2c 8c Qs
mrC       797820635  7  1 +Bc   c      r      b        b          480  110  290 2s 4h 3d 6h
mrC       797820700  7  7  c   +k     +b     +bc      +kr         660  110  150 4h 4c 2c 7d  5c As Kc
mrC       797820801  7  6  f    -      -      -        -          700    0    0 7h
mrC       797820864  8  6  f    -      -      -        -          700    0    0 Js
mrC       797820984  8  2  f    -      -      -        -          700    0    0 6h
mrC       797821021  8  8  f    -      -      -        -          700    0    0 Tc
mrC       797821067  8  6  f    -      -      -        -          700    0    0 8d
mrC       797821238  7  4  f    -      -      -        -          700    0    0 6c
mrC       797821330  7  6  Q    -      -      -        -          700    0    0 3s
