DM        808372549  3  2  rc  +kc    +kc    +kc      +k         2910   80    0 Ac 5d Js Tc  8c 3d 8h
DM        808372582  5  4  c    kf     -      -        -         2830   10    0 7d Ks
DM        808372666  5  2  r   +b     +k     +bc      +k         2820   70    0 As Jc 4h Td  Qd Tc 8s
DM        808372726  5  4  f    -      -      -        -         2750    0    0 3s
DM        808372774  5  1 +Bk   f      -      -        -         2750   10    0 4h Ks
DM        808372826  5  2  cc  +kcc   +k     +k       +k         2740   40  130 Td As Kc 7c  Tc 6s 6d
DM        808372901  5  4  fQ   -      -      -        -         2830    0    0 Js
DM        808373615  6  4  cc  +kc    +kf     -        -         2830   30    0 9d Ad Kc
DM        808373699  6  4  f    -      -      -        -         2800    0    0 Th
DM        808373757  6  4  cc   kc     kc    +k       +kc        2800   70   85 7c 3s 9c Qd  4s 9s 7d
DM        808373841  6  2  f    -      -      -        -         2815    0    0 9c
DM        808373863  6  3  f    -      -      -        -         2815    0    0 Jh
DM        808373928  6  3  f    -      -      -        -         2815    0    0 Tc
DM        808374002  6  3  f    -      -      -        -         2815    0    0 9c
DM        808374023  6  6  r    b     +bc     kc       k         2815   90    0 4s 5h 5c 7d  7h 3c 4h
DM        808374114  6  5  c   +k     +kc    +k       +kc        2725   50   50 3c Qd 7d 7s  3d 4h Kc
DM        808374164  6  2  c    kc    +b     +b       +kc        2725   80  130 Jh Tc Jc 4d  8h Th 6h
DM        808374265  6  3  c    kc     k     +kcc     +kc        2775  120    0 5h Ts 7h As  6c 5d 8h
DM        808374372  6  2  Q    -      -      -        -         2655    0    0 9c
DM        808374620  7  2  f    -      -      -        -         2655    0    0 5s
DM        808374659  7  7  f    -      -      -        -         2655    0    0 9c
DM        808374782  7  4  f    -      -      -        -         2655    0    0 9h
DM        808374879  7  2  f    -      -      -        -         2655    0    0 Ks
DM        808375006  7  1 +Bk   k      f      -        -         2655   10    0 3d Kc Qs
DM        808375095  8  1 +Brcc  rc     c      c        kf        2645  120    0 2s 4d Kd 4c
DM        808375338  7  6  cc   kc     f      -        -         2525   60    0 7s 6h Ks
DM        808375490  8  1 +Bf   -      -      -        -         2465   10    0 2h
DM        808375820  8  2  f    -      -      -        -         2455    0    0 3h
DM        808376041  7  1 +Br   r      bc     kc       b         2455  120  220 3d 7h 2c Tc  2s 2h 4d
DM        808376251  3  2  Q    -      -      -        -         2555    0    0 Kh
