Bison     823286052  8  6  f    -      -      -        -         1160    0    0 8h
Bison     823286105  8  7  f    -      -      -        -         1160    0    0 9d
Bison     823286179  8  8  c    k      b     +bc      +kc        1160   90    0 6h 9c Qs Ad  Qd 6d 9s
Bison     823286351  8  8  c    f      -      -        -         1070   10    0 4s 2d
Bison     823286424  8  2  f    -      Q      -        -         1060    0    0 7c
