Bison     822647744  2  1 +BQ   -      -      -        -         1000   10    0 9h
Bison     822798478  5  3  f    -      -      -        -          990    0    0 4d
Bison     822798545  5  1 +Bc   f      -      -        -          990   20    0 3h Kh
Bison     822798709  6  5  c   +bc    +k     +b       +b          970   70  150 7c 7d Jc 7s
Bison     822798892  5  5  f    -      -      -        -         1050    0    0 3d
Bison     822798990  5  5  f    -      -      -        -         1050    0    0 9h
Bison     822799093  5  2  f    -      -      -        -         1050    0    0 5s
Bison     822799161  5  3  c   +b     +k     +br      +k         1050   80  200 9c Ad 9d Qs  6d 9s Th
Bison     822799250  5  4  c    f      Q      -        -         1170   10    0 7s Qd
