Dylan     853236883  4  4  c    kc    +kf     -        -         1000   30    0 7h 3c Qc
Dylan     853236963  4  1 +B    -      -      -        -          970   10   10 8d
Dylan     853237001  3  3  f    -      -      -        -          970    0    0 6s
Dylan     853237049  3  2  rc   c     +kc    +b       +b          970  100  220 Qs 6d Kh 7s
Dylan     853237147  3  2  f    -      -      -        -         1090    0    0 Js
Dylan     853237220  3  3  c    c      c     +k       +bc        1090  110  145 8s 6s Tc Qh  5c 2s 4s
Dylan     853237304  3  2  r   +kc    +k     +b       +kc        1125   70    0 Jc Qc Ac 6h  5d Tc Ad
Dylan     853237382  3  3  c   +b     +b     +b       +k         1055   60    0 6h Jc 4c 4d  8h Qc 3c
Dylan     853237451  4  1 +Bc   c      b      k        b          995   70  140 7h 4h Kh Tc
Dylan     853237523  4  2  c    b      b      c        c         1065   80   85 4c 7s 3h 8c  2d 5d Qd
Dylan     853237610  5  4  f    -      -      -        -         1070    0    0 6s
Dylan     853237680  5  2  r    k      cf     -        -         1070   40    0 Qh 3d 4h
Dylan     853237841  5  5  f    -      -      -        -         1030    0    0 4d
Dylan     853237900  5  5  c   +k      r      c        c         1030   90    0 Ks 2c 5d 9h  2h 6c 4s
Dylan     853237976  5  3  c   +k     +bc    +b       +b          940   90  105 Ah As Qc 2h  Tc 8h Qs
Dylan     853238068  5  5  f    -      -      -        -          955    0    0 Ts
Dylan     853238143  6  6  c    c      kf     -        -          955   20    0 9c 7s Ts
Dylan     853238214  6  5  c   +bc    +kr    +b       +b          935  110  202 7s Kc 4d As  5c 8s 8d
Dylan     853238318  7  2  c    c      f      -        -         1027   20    0 5s 3h 9h
Dylan     853238475  6  2  f    -      -      -        -         1007    0    0 9h
Dylan     853238623  7  3  c    c      r      b        kc        1007  120    0 4h 8h 8c 5d  4s Qh 6s
Dylan     853238823  6  3  c    c      c      k        b          887   60  140 9s 6h Tc 4s
Dylan     853238971  7  5  c    b      b     +b       +k          967   70   90 Qc Js 7d 7s  4c 2d Jc
Dylan     853239095  6  6  f    -      -      -        -          987    0    0 9s
Dylan     853239136  6  2  cc   f      -      -        -          987   20    0 5h Ks
Dylan     853239243  6  5  c    c      cc     f        -          967  100    0 Qs 5d 5c 8d
Dylan     853239447  7  5  c   +kc     cc     kf       -          867   80    0 4s 4h Tc Qd
Dylan     853239635  7  3  c    c      b      b        k          787   60    0 5s 3h Js 8s  5c Jh 2c
Dylan     853239737  7  3  f    -      -      -        -          727    0    0 Td
Dylan     853239803  7  1 +Bk   f      -      -        -          727   10    0 3d 5d
Dylan     853239895  6  4  f    -      -      -        -          717    0    0 Ks
Dylan     853240018  6  5  cc   c      c      kf       -          717   70    0 9s Qc 6h Ac
Dylan     853240224  6  1 +Bc   r      c      f        -          647   60    0 2h 6h Jc Td
Dylan     853240306  7  3  r    b      cc     k        c          587  110    0 6c 2h Th Qd  Ac 5h Ad
Dylan     853240515  7  5  c    c      f      -        -          477   40    0 9d 2d Tc
Dylan     853240689  7  2  c    kf     -      -        -          437   10    0 Th 8c
Dylan     853240823  7  7  f    -      -      -        -          427    0    0 Kd
Dylan     853240929  7  1 +Bk   c      r      c        c          427  100    0 4d 6c Kd Qd  3s 2s Ks
Dylan     853241046  7  4  f    -      -      -        -          327    0    0 9h
Dylan     853241265  7  5  c   +b     +k     +b       +bf         327   60    0 Ac Qc 7d 3s
Dylan     853241379  7  1 +Bc   c      f      -        -          267   30    0 2h 9c 2d
Dylan     853241475  7  2  f    -      -      -        -          237    0    0 Jd
Dylan     853241561  7  6  f    -      -      -        -          237    0    0 4c
Dylan     853241680  7  2  cc   f      -      -        -          237   20    0 7d 8c
Dylan     853241971  6  3  c    f      -      -        -          217   20    0 5h Tc
Dylan     853242239  6  2  f    -      -      -        -          197    0    0 Td
Dylan     853242378  6  1 +Bk  +kc    +k     +kf       -          197   20    0 3s 7s 7d Jh
Dylan     853242462  7  3  f    -      -      -        -          177    0    0 Tc
Dylan     853242604  7  5  f    -      -      -        -          177    0    0 Ac
Dylan     853242752  8  2  f    -      -      -        -          177    0    0 Qs
Dylan     853242832  7  2  f    -      -      -        -          177    0    0 7s
Dylan     853242904  8  8  f    -      -      -        -          177    0    0 4c
Dylan     853243080  7  6  c    b     +bc    +kc      +kc         177  100    0 7c 8s 8h 9c  7h 5s 3h
Dylan     853243230  6  6  f    -      -      -        -           77    0    0 Js
Dylan     853243294  6  4  f    -      -      -        -           77    0    0 8d
Dylan     853243423  7  3  c    c     +kc    +kc      +bA          77   77  142 Kc 3h Kd 6h  8c 2d Ad
Dylan     853243610  8  8  c   +bcc    f      -        -          142   60    0 Kd As 9c
Dylan     853243853  8  1 +Bk   r      b      k        f           82   50    0 5c 4h 8h Th
Dylan     853243974  7  4  f    -      -      -        -           32    0    0 Kd
Dylan     853244086  7  7  c    c      cA     -        -           32   32  136 3c 2d Qs Ts  6h Tc 6s
Dylan     853244160  6  1 +Bk   b      c      c        k          136   60    0 4c 3h Jd 2c  6c 3c Qd
Dylan     853244248  6  3  f    -      -      -        -           76    0    0 Qs
Dylan     853244303  5  2  cc   c      kc     k        f           76   50    0 Th 3d 6s Qs
Dylan     853244408  5  4  f    -      -      -        -           26    0    0 Ks
Dylan     853244443  5  1 +Bk   b      bA     -        -           26   26    0 5d 8h 7s  Ks 5s Ad Qs
Dylan     853244544  4  1 +Bf   -      -      -        -         1000   10    0 6c
Dylan     853244600  3  3  r    b      b      b        b          990   90  125 As 2s 4s 8c  6h Jd 5d
Dylan     853244663  3  1 +Bk   c      r      b        b         1025  100  105 4d 7s 6c Ad  8d 3d 5d
Dylan     853244737  3  3  r   +b      k      k        k         1030   30    0 Kc Ad 6s Qd  2h 6c 8h
Dylan     853244779  3  1 +Bk   k      c      f        -         1000   30    0 9c 4c 6s Ts
Dylan     853244826  3  3  c   +b      kc     kc       bc         970  100    0 As 7h Td 2d  8s 8h 6h
Dylan     853244892  3  1 +Bk  +f      -      -        -          870   10    0 7s Qs
Dylan     853244943  3  2  r    k      b      k        b          860   60  140 6d Tc 7h Jc
Dylan     853244994  3  3  c    b      b      -        -          940   40   60 7c 4c 3c
Dylan     853245032  3  2  f    -      -      -        -          960    0    0 Qs
Dylan     853245064  3  3  f    -      -      -        -          960    0    0 8h
Dylan     853245079  3  2  rc  +k     +kc    +b       +b          960   90  250 6h Kd 7c 5d  4h 3s Jc
Dylan     853245147  3  1 +Bk   b      b      b        k         1120   60   60 2s 3h 7s 2c  6c Qc As
Dylan     853245189  3  1 +Bk   k      k      f        -         1120   10    0 4h Kc 7d 9s
Dylan     853245238  3  1 +Bk   k     +k     +bc      +kc        1110   70    0 2c 5h Qs 5s  Td Js 3h
Dylan     853245294  3  3  f    -      -      -        -         1040    0    0 8d
Dylan     853245341  3  2  c   +b     +kc    +kf       -         1040   40    0 Td 2h Jh 4h
Dylan     853245391  3  1 +Bk   b      b      c        k         1000   60  160 5s 4d 7d 9s  Js 3h 6c
Dylan     853245459  3  3  c   +kf     -      -        -         1100   10    0 Ad 6h
Dylan     853245499  3  1 +Br   b      b      -        -         1090   50   80 5d 7h 2h
Dylan     853245529  3  3  f    -      -      -        -         1120    0    0 4c
Dylan     853245557  3  3  f    -      -      -        -         1120    0    0 Kh
Dylan     853245592  3  1 +Br  +b      b      b        k         1120   70    0 4h 6c 8h Kc  8d Th 3c
Dylan     853245636  3  2  r    c      k      f        -         1050   30    0 6c 9c 7s Ac
Dylan     853245691  3  2  r    k      k      r        k         1020   60    0 6h Qh Jd 2c  5c 4c 6s
Dylan     853245736  3  3  c    b     +b     +b        -          960   60  100 8c 7d Kd 7s
Dylan     853245785  3  1 +Bk  +b     +b     +b       +k         1000   60  130 5d Ad Th Jc  Jd 5c Qh
Dylan     853245822  3  3  c   +b     +b     +b       +k         1070   60  120 Ac Ah As 8c  6s Th 3c
Dylan     853245866  3  3  f    -      -      -        -         1130    0    0 Qs
Dylan     853245900  3  3  r   +k     +k      r        b         1130   80    0 7c As Qh 8d  Jc Qs 8c
Dylan     853245943  3  2  f    -      -      -        -         1050    0    0 Js
Dylan     853245968  3  2  r   +b     +b     +b       +b         1050   90  125 Jc 4h 7c 9c  Jd Ks Kc
Dylan     853246013  3  1 +B    -      -      -        -         1085   10   10 3s
Dylan     853246026  3  3  r   +k      b     +b       +kc        1085   80    0 7s Ks Td Th  4s 2c As
Dylan     853246069  3  1 +Bf   -      -      -        -         1005   10    0 7s
Dylan     853246087  3  1 +Bk   c      rc     c        f          995  100    0 3d Qs 4h Jh
Dylan     853246151  3  2  Q    -      -      -        -          895    0    0 5h
Dylan     854145283  5  5  c   +Q      -      -        -          895   10    0 9c 9h
