mel       818724846  5  5 c   b     b     f          884   40    0 
mel       818724915  5  4 c   f     -     -          844   10    0 
mel       818724969  5  3 c   k     c     b          834   50   65 Th Jd 9c 4h
mel       818725026  4  2 Bk  c     f     -          849   20    0 
mel       818725083  4  1 Bc  k     kc    kc         829   50   75 Qs Kd Js 9s
mel       818725138  4  4 c   c     rrc   rrr        854  240  265 2s 3h 3c 9d
mel       818725235  4  3 r   kc    k     k          879   30   38 Qc Th 7c Qh
mel       818725298  4  2 Bk  c     f     -          887   20    0 
mel       818725348  4  1 Br  kc    b     b          867   70  160 Tc Jh Ad 2h
mel       818725400  3  3 c   r     k     c          957   50   55 Qs 6h Kh Qc
mel       818725454  2  2 c   bQ    -     -          962   20    0 
mel       818980243  7  7 c   f     -     -          942   10    0 
mel       818980318  6  5 cc  br    r     Q          932  100    0 
mel       818981472  7  6 f   -     -     -          832    0    0 
mel       818981521  7  5 c   b     bc    c          832   90    0 2h 4c Jh 4d
mel       818981625  7  4 cc  b     -     -          742   30   80 
mel       818981695  7  3 cc  kf    -     -          792   20    0 
mel       818981799  7  2 Bk  b     kc    b          772   60   83 8s Jc 9c 3c
mel       818981874  7  1 Bc  b     bc    kc         795   90    0 5h As 3d Qh
mel       818981981  7  7 c   f     -     -          705   10    0 
mel       818982109  8  6 c   c     c     k          695   40    0 Ad 3h Qs 8h
mel       818982180  7  5 c   c     c     f          655   40    0 
mel       818982258  7  4 f   -     -     -          615    0    0 
mel       818982319  7  3 c   f     -     -          615   10    0 
mel       818982375  7  2 Bk  kc    k     kc         605   40    0 Td Qc Jh Qs
mel       818982470  7  1 Bc  kc    kc    kc         565   60    0 Ad 8c Jc 9h
mel       818982570  7  7 fQ  -     -     -          505    0    0 
