mac       934313884  9  6 cc  c     c     c         1000   70    0 6d 9s 2c Js
mac       934313977  8  4 rc  bc    kc    f          930   70    0 
mac       934314060  8  3 c   r     r     b          860   90    0 Js 5s 4s 8s
mac       934314158  5  2 Bc  k     k     k          770   20    0 Qd Ts 4d Jc
mac       934314256  5  1 Bf  -     -     -          750    5    0 
mac       934314281  4  4 f   -     -     -          745    0    0 
mac       934314345  4  4 f   Q     -     -          745    0    0 
