Pogo      917579008  6  6 rr  b     b     b          786   90    0 Ad 2h Td Ac
Pogo      917579281  4  3 f   -     -     -          696    0    0 
Pogo      917579333  4  3 f   -     -     -          696    0    0 
Pogo      917579391  7  2 Bk  kc    kr    bc         696  100  215 6c 9c 7h Qc
Pogo      917579445  8  1 Bc  k     kf    -          811   10    0 
Pogo      917579511  8  8 c   k     k     f          801   10    0 
Pogo      917579582  8  7 c   b     b     k          791   40    0 5h 3h Kd Kh
Pogo      917579684  8  6 cc  c     b     k          751   50  300 Ad Qs Jc 5s
Pogo      917579782  9  5 Q   -     -     -         1001    0    0 
Pogo      917580976  9  6 c   c     f     -         1001   20    0 
Pogo      917581068 10  5 fQ  -     -     -          981    0    0 
