CJ        860685613  2  2 BrrA -     -     -           50   50    0 3d Jd 6h 8c
CJ        860685643  2  2 Brrrrrrrrrrf -     -     -         1000  210    0 
CJ        860685675  2  1 Bc  kc    brrrrrrrrrrf -          790  440    0 
CJ        860685731  2  2 Bk  k     rrrrrrrrcA -          350  350  350 8c 3c 6h 6c
CJ        860685767  2  1 Bcc k     brrrrf -          350  200    0 
CJ        860685807  2  2 Bk  k     rrf   -          150   90    0 
CJ        860685838  2  1 Bc  b     b     bA          60   60    0 4s 2h Qd 2s
CJ        860685909  2  2 Brc rrrrc c     rrrrrrrrrrrrrrrrrrrrrcA   1000 1000    0 Ac 4d 7h Qd
