G         891760315  3  3 crrrrrrrrrrrrr b     rrrrrrrrrrrrrrrrrrrrrr -         2445 2320 4610 
G         891760407  2  2 Brrr r     rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr -         4735 4420 8800 
G         891760456  2  1 Brrr br    brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr -         9115 8300 16560 
G         891760504  2  2 Brr brrrr rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrc c        17375 3160    0 6d 9s
G         891760517  2  1 Bcc br    b     brrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrQ  14215 8740 17520 
