Trigger   895340659 10  8 f   -     -     -         1000    0    0 
Trigger   895340724 10  7 c   c     c     f         1000   40    0 
Trigger   895340788  8  4 f   -     -     -          960    0    0 
Trigger   895340845 10  3 f   -     -     -          960    0    0 
Trigger   895340905 10  2 Bf  -     -     -          960   10    0 
Trigger   895340939  9  1 Bc  k     kc    br         950   90    0 5h Th
Trigger   895341040  9  9 f   -     -     -          860    0    0 
Trigger   895341089  9  8 r   b     c     c          860   70    0 Qc Qd
Trigger   895341156  9  7 f   -     -     -          790    0    0 
Trigger   895341191 10  6 f   -     -     -          790    0    0 
Trigger   895341205 10  5 f   -     -     -          790    0    0 
Trigger   895341256  9  5 f   -     -     -          790    0    0 
Trigger   895341309  8  3 f   -     -     -          790    0    0 
Trigger   895341358  9  2 Bcc kc    kc    kf         790   60    0 
Trigger   895341434 10  1 Bc  kf    -     -          730   10    0 
Trigger   895341478  9  9 f   -     -     -          720    0    0 
Trigger   895341511  9  8 f   -     -     -          720    0    0 
Trigger   895341554  9  7 r   f     -     -          720   20    0 
Trigger   895341618  9  6 f   -     -     -          700    0    0 
Trigger   895341658  9  5 cc  bc    kc    kr         700  100  215 Ts Ah
Trigger   895341712  9  4 f   -     -     -          815    0    0 
Trigger   895341753 10  4 cf  -     -     -          815   10    0 
Trigger   895341814  9  3 f   -     -     -          805    0    0 
Trigger   895341866  9  2 Bf  -     -     -          805   10    0 
Trigger   895341881  9  1 Bc  kc    k     k          795   20   30 3c Kd
Trigger   895341933 10 10 f   -     -     -          805    0    0 
Trigger   895341971  9  3 Q   -     -     -          805    0    0 
