Coffee    849778274  5  2 Bk  k     k     k         1000   10    0 Qs 6d
Coffee    849778328  4  1 Bc  kf    -     -          990   10    0 
Coffee    849778388  4  4 c   f     -     -          980   10    0 
Coffee    849778462  4  3 c   c     c     f          970   40    0 
Coffee    849778522  4  2 Bk  bc    krc   kf         930   90    0 
Coffee    849778590  5  1 Bf  -     -     -          840    5    0 
Coffee    849778686  5  5 rc  b     b     r          835  100  225 
Coffee    849778810  5  4 cc  f     -     -          960   20    0 
Coffee    849778924  5  3 f   -     -     -          940    0    0 
Coffee    849778989  5  2 Br  b     b     kc         940   70    0 As Js
Coffee    849779078  5  1 Bc  kf    -     -          870   10    0 
Coffee    849779121  5  5 rr  f     -     -          860   40    0 
Coffee    849779254  6  5 c   cc    k     k          820   30   50 9h Th
Coffee    849779406  5  3 f   -     -     -          840    0    0 
Coffee    849779480  5  2 Bk  kc    k     kf         840   20    0 
Coffee    849779638  5  1 Bf  -     -     -          820    5    0 
Coffee    849779708  5  5 f   -     -     -          815    0    0 
Coffee    849779797  4  3 c   b     b     -          815   40   70 
Coffee    849779842  4  2 Bk  kf    -     -          845   10    0 
Coffee    849779928  5  1 Bc  kc    kf    -          835   20    0 
Coffee    849779966  5  5 f   -     -     -          815    0    0 
Coffee    849780018  5  4 f   -     -     -          815    0    0 
Coffee    849780080  5  3 r   c     c     c          815   70    0 As 5s
Coffee    849780140  5  2 Bk  k     kc    k          745   30  100 Js 2c
Coffee    849780210  5  1 Bc  k     kf    -          815   10    0 
Coffee    849780260  5  5 f   -     -     -          805    0    0 
Coffee    849780364  5  4 f   -     -     -          805    0    0 
Coffee    849780430  5  3 c   kc    kc    kc         805   60    0 4s Ac
Coffee    849780498  5  2 Bk  k     b     kr         745   70  170 Ts 4s
Coffee    849780592  5  1 Br  b     b     k          845   50   75 Kd Qc
Coffee    849780664  3  3 f   -     -     -          870    0    0 
Coffee    849780706  3  3 f   -     -     -          870    0    0 
Coffee    849780746  3  2 Bc  kf    -     -          870   20    0 
Coffee    849780771  3  1 Bcc kc    kc    k          850   50  120 9d Ac
Coffee    849780821  3  3 f   -     -     -          920    0    0 
Coffee    849780850  3  2 Bcc k     k     f          920   30    0 
Coffee    849780921  4  1 Bc  k     b     -          890   30   60 
Coffee    849780964  4  4 r   b     c     c          920   70    0 8d 2d
Coffee    849781037  4  3 cr  fQ    -     -          850   40    0 
