Dylan     860465564  7  3  f    -      -      -        -          885    0    0 7h
Dylan     860465623  7  4  cc   c      b     +b       +b          885   90    0 6s 9c Ad 6h  2h 2s 5c
Dylan     860465727  7  7  c    r      r      b       +b          795  110  280 8h 4d 6d Kd
Dylan     860465828  6  6  cc   b     +bcc   +kc      +kf         965  130    0 3s 4h 4s Ks
Dylan     860465930  6  1 +Bf   -      -      -        -          835   10    0 7d
Dylan     860466008  6  1 +BQ   -      -      -        -          825   10    0 2c
